// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: credentials.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const accessCredential = `-- name: AccessCredential :one
UPDATE credentials
SET last_accessed = NOW()
WHERE credentials.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
RETURNING id, uuid, name, key_type, key_data, namespace_id, last_accessed, created_at, updated_at
`

type AccessCredentialParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) AccessCredential(ctx context.Context, arg AccessCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, accessCredential, arg.Uuid, arg.Uuid_2)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyType,
		&i.KeyData,
		&i.NamespaceID,
		&i.LastAccessed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (name, key_type, key_data, namespace_id)
VALUES ($1, $2, $3, (SELECT id FROM namespaces WHERE namespaces.uuid = $4))
RETURNING id, uuid, name, key_type, key_data, namespace_id, last_accessed, created_at, updated_at
`

type CreateCredentialParams struct {
	Name    string    `db:"name" json:"name"`
	KeyType string    `db:"key_type" json:"key_type"`
	KeyData string    `db:"key_data" json:"key_data"`
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.Name,
		arg.KeyType,
		arg.KeyData,
		arg.Uuid,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyType,
		&i.KeyData,
		&i.NamespaceID,
		&i.LastAccessed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE credentials.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteCredentialParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, arg.Uuid, arg.Uuid_2)
	return err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT c.id, c.uuid, c.name, c.key_type, c.key_data, c.namespace_id, c.last_accessed, c.created_at, c.updated_at, ns.uuid AS namespace_uuid FROM credentials c
JOIN namespaces ns ON c.namespace_id = ns.id
WHERE c.id = $1 AND ns.uuid = $2
`

type GetCredentialByIDParams struct {
	ID   int32     `db:"id" json:"id"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

type GetCredentialByIDRow struct {
	ID            int32        `db:"id" json:"id"`
	Uuid          uuid.UUID    `db:"uuid" json:"uuid"`
	Name          string       `db:"name" json:"name"`
	KeyType       string       `db:"key_type" json:"key_type"`
	KeyData       string       `db:"key_data" json:"key_data"`
	NamespaceID   int32        `db:"namespace_id" json:"namespace_id"`
	LastAccessed  sql.NullTime `db:"last_accessed" json:"last_accessed"`
	CreatedAt     time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID    `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetCredentialByID(ctx context.Context, arg GetCredentialByIDParams) (GetCredentialByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, arg.ID, arg.Uuid)
	var i GetCredentialByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyType,
		&i.KeyData,
		&i.NamespaceID,
		&i.LastAccessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const getCredentialByUUID = `-- name: GetCredentialByUUID :one
SELECT c.id, c.uuid, c.name, c.key_type, c.key_data, c.namespace_id, c.last_accessed, c.created_at, c.updated_at, ns.uuid AS namespace_uuid FROM credentials c
JOIN namespaces ns ON c.namespace_id = ns.id
WHERE c.uuid = $1 AND ns.uuid = $2
`

type GetCredentialByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetCredentialByUUIDRow struct {
	ID            int32        `db:"id" json:"id"`
	Uuid          uuid.UUID    `db:"uuid" json:"uuid"`
	Name          string       `db:"name" json:"name"`
	KeyType       string       `db:"key_type" json:"key_type"`
	KeyData       string       `db:"key_data" json:"key_data"`
	NamespaceID   int32        `db:"namespace_id" json:"namespace_id"`
	LastAccessed  sql.NullTime `db:"last_accessed" json:"last_accessed"`
	CreatedAt     time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID    `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetCredentialByUUID(ctx context.Context, arg GetCredentialByUUIDParams) (GetCredentialByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByUUID, arg.Uuid, arg.Uuid_2)
	var i GetCredentialByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyType,
		&i.KeyData,
		&i.NamespaceID,
		&i.LastAccessed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const searchCredentials = `-- name: SearchCredentials :many
WITH filtered AS (
    SELECT c.id, c.uuid, c.name, c.key_type, c.key_data, c.namespace_id, c.last_accessed, c.created_at, c.updated_at, ns.uuid AS namespace_uuid FROM credentials c
    JOIN namespaces ns ON c.namespace_id = ns.id
    WHERE ns.uuid = $1 AND (
        $4 = '' OR
        c.name ILIKE '%' || $4::text || '%'
    )
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, key_type, key_data, namespace_id, last_accessed, created_at, updated_at, namespace_uuid FROM filtered
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.uuid, p.name, p.key_type, p.key_data, p.namespace_id, p.last_accessed, p.created_at, p.updated_at, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchCredentialsParams struct {
	Uuid    uuid.UUID   `db:"uuid" json:"uuid"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
	Column4 interface{} `db:"column_4" json:"column_4"`
}

type SearchCredentialsRow struct {
	ID            int32        `db:"id" json:"id"`
	Uuid          uuid.UUID    `db:"uuid" json:"uuid"`
	Name          string       `db:"name" json:"name"`
	KeyType       string       `db:"key_type" json:"key_type"`
	KeyData       string       `db:"key_data" json:"key_data"`
	NamespaceID   int32        `db:"namespace_id" json:"namespace_id"`
	LastAccessed  sql.NullTime `db:"last_accessed" json:"last_accessed"`
	CreatedAt     time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time    `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID    `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount     int64        `db:"page_count" json:"page_count"`
	TotalCount    int64        `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchCredentials(ctx context.Context, arg SearchCredentialsParams) ([]SearchCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCredentials,
		arg.Uuid,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCredentialsRow
	for rows.Next() {
		var i SearchCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.KeyType,
			&i.KeyData,
			&i.NamespaceID,
			&i.LastAccessed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET name = $2, key_type = $3, key_data = $4, updated_at = NOW()
WHERE credentials.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $5)
RETURNING id, uuid, name, key_type, key_data, namespace_id, last_accessed, created_at, updated_at
`

type UpdateCredentialParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Name    string    `db:"name" json:"name"`
	KeyType string    `db:"key_type" json:"key_type"`
	KeyData string    `db:"key_data" json:"key_data"`
	Uuid_2  uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.Uuid,
		arg.Name,
		arg.KeyType,
		arg.KeyData,
		arg.Uuid_2,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.KeyType,
		&i.KeyData,
		&i.NamespaceID,
		&i.LastAccessed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
