// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: credentials.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (name, private_key, password)
VALUES ($1, $2, $3)
RETURNING id, uuid, name, private_key, password, created_at, updated_at
`

type CreateCredentialParams struct {
	Name       string         `db:"name" json:"name"`
	PrivateKey sql.NullString `db:"private_key" json:"private_key"`
	Password   sql.NullString `db:"password" json:"password"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential, arg.Name, arg.PrivateKey, arg.Password)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE uuid = $1
`

func (q *Queries) DeleteCredential(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, argUuid)
	return err
}

const getCredentialByID = `-- name: GetCredentialByID :one
SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials WHERE id = $1
`

func (q *Queries) GetCredentialByID(ctx context.Context, id int32) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByUUID = `-- name: GetCredentialByUUID :one
SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials WHERE uuid = $1
`

func (q *Queries) GetCredentialByUUID(ctx context.Context, argUuid uuid.UUID) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByUUID, argUuid)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, uuid, name, private_key, password, created_at, updated_at FROM credentials
`

func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.PrivateKey,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET name = $2, private_key = $3, password = $4, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, private_key, password, created_at, updated_at
`

type UpdateCredentialParams struct {
	Uuid       uuid.UUID      `db:"uuid" json:"uuid"`
	Name       string         `db:"name" json:"name"`
	PrivateKey sql.NullString `db:"private_key" json:"private_key"`
	Password   sql.NullString `db:"password" json:"password"`
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.Uuid,
		arg.Name,
		arg.PrivateKey,
		arg.Password,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.PrivateKey,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
