// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cron_schedules.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCronSchedule = `-- name: CreateCronSchedule :one
INSERT INTO cron_schedules (flow_id, cron, timezone)
VALUES ($1, $2, $3)
RETURNING id, flow_id, cron, timezone, created_at, updated_at
`

type CreateCronScheduleParams struct {
	FlowID   int32  `db:"flow_id" json:"flow_id"`
	Cron     string `db:"cron" json:"cron"`
	Timezone string `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateCronSchedule(ctx context.Context, arg CreateCronScheduleParams) (CronSchedule, error) {
	row := q.db.QueryRowContext(ctx, createCronSchedule, arg.FlowID, arg.Cron, arg.Timezone)
	var i CronSchedule
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Cron,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCronSchedulesByFlowID = `-- name: DeleteCronSchedulesByFlowID :exec
DELETE FROM cron_schedules
WHERE flow_id = $1
`

func (q *Queries) DeleteCronSchedulesByFlowID(ctx context.Context, flowID int32) error {
	_, err := q.db.ExecContext(ctx, deleteCronSchedulesByFlowID, flowID)
	return err
}

const getAllCronSchedules = `-- name: GetAllCronSchedules :many
SELECT cs.id, cs.flow_id, cs.cron, cs.timezone, cs.created_at, cs.updated_at, f.slug AS flow_slug, f.name AS flow_name, n.uuid AS namespace_uuid
FROM cron_schedules cs
JOIN flows f ON cs.flow_id = f.id
JOIN namespaces n ON f.namespace_id = n.id
WHERE f.is_active = TRUE
ORDER BY cs.flow_id, cs.id
`

type GetAllCronSchedulesRow struct {
	ID            int32     `db:"id" json:"id"`
	FlowID        int32     `db:"flow_id" json:"flow_id"`
	Cron          string    `db:"cron" json:"cron"`
	Timezone      string    `db:"timezone" json:"timezone"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
	FlowSlug      string    `db:"flow_slug" json:"flow_slug"`
	FlowName      string    `db:"flow_name" json:"flow_name"`
	NamespaceUuid uuid.UUID `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetAllCronSchedules(ctx context.Context) ([]GetAllCronSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCronSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllCronSchedulesRow
	for rows.Next() {
		var i GetAllCronSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Cron,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FlowSlug,
			&i.FlowName,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCronSchedulesByFlowID = `-- name: GetCronSchedulesByFlowID :many
SELECT id, flow_id, cron, timezone, created_at, updated_at FROM cron_schedules
WHERE flow_id = $1
ORDER BY id
`

func (q *Queries) GetCronSchedulesByFlowID(ctx context.Context, flowID int32) ([]CronSchedule, error) {
	rows, err := q.db.QueryContext(ctx, getCronSchedulesByFlowID, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CronSchedule
	for rows.Next() {
		var i CronSchedule
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Cron,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
