// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: execution.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
)

const addExecutionLog = `-- name: AddExecutionLog :one
INSERT INTO execution_log (
    exec_id,
    flow_id,
    input,
    triggered_by
) VALUES (
    $1, $2, $3, $4
) RETURNING id, exec_id, flow_id, input, output, error, status, triggered_by, created_at
`

type AddExecutionLogParams struct {
	ExecID      string          `db:"exec_id" json:"exec_id"`
	FlowID      int32           `db:"flow_id" json:"flow_id"`
	Input       json.RawMessage `db:"input" json:"input"`
	TriggeredBy int32           `db:"triggered_by" json:"triggered_by"`
}

func (q *Queries) AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, addExecutionLog,
		arg.ExecID,
		arg.FlowID,
		arg.Input,
		arg.TriggeredBy,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE execution_log SET status=$1, output=$2, error=$3 WHERE exec_id = $4 RETURNING id, exec_id, flow_id, input, output, error, status, triggered_by, created_at
`

type UpdateExecutionStatusParams struct {
	Status ExecutionStatus `db:"status" json:"status"`
	Output json.RawMessage `db:"output" json:"output"`
	Error  sql.NullString  `db:"error" json:"error"`
	ExecID string          `db:"exec_id" json:"exec_id"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.Output,
		arg.Error,
		arg.ExecID,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Input,
		&i.Output,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
	)
	return i, err
}
