// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: execution.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const addExecutionLog = `-- name: AddExecutionLog :one
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $4
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $5
), next_version AS (
    SELECT COALESCE(MAX(version), -1) + 1 as version
    FROM execution_log
    WHERE exec_id = $1 AND namespace_id = (SELECT id FROM namespace_lookup)
), prev_action_retries AS (
    SELECT action_retries
    FROM execution_log
    WHERE exec_id = $1 AND namespace_id = (SELECT id FROM namespace_lookup)
    ORDER BY version DESC
    LIMIT 1
)
INSERT INTO execution_log (
    exec_id,
    flow_id,
    version,
    input,
    trigger_type,
    triggered_by,
    namespace_id,
    action_retries
) VALUES (
    $1, $2, (SELECT version FROM next_version), $3, $6, (SELECT id FROM user_lookup), (SELECT id FROM namespace_lookup),
    COALESCE((SELECT action_retries FROM prev_action_retries), '{}')
) RETURNING id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries
`

type AddExecutionLogParams struct {
	ExecID      string          `db:"exec_id" json:"exec_id"`
	FlowID      int32           `db:"flow_id" json:"flow_id"`
	Input       json.RawMessage `db:"input" json:"input"`
	Uuid        uuid.UUID       `db:"uuid" json:"uuid"`
	Uuid_2      uuid.UUID       `db:"uuid_2" json:"uuid_2"`
	TriggerType TriggerType     `db:"trigger_type" json:"trigger_type"`
}

func (q *Queries) AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, addExecutionLog,
		arg.ExecID,
		arg.FlowID,
		arg.Input,
		arg.Uuid,
		arg.Uuid_2,
		arg.TriggerType,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
	)
	return i, err
}

const executionExistsForFlow = `-- name: ExecutionExistsForFlow :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
),
latest_versions AS (
    SELECT exec_id, MAX(version) as max_version
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
    GROUP BY exec_id
)
SELECT exists (SELECT id, el.exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries, lv.exec_id, max_version FROM execution_log el INNER JOIN latest_versions lv on el.exec_id = lv.exec_id
WHERE flow_id = (SELECT id FROM flows WHERE flows.slug = $1 AND flows.namespace_id = (SELECT id FROM namespace_lookup) AND flows.is_active = TRUE) AND
namespace_id = (SELECT id FROM namespace_lookup) AND
(status = 'running' or status = 'pending_approval' or status = 'pending') AND
version = lv.max_version)
`

type ExecutionExistsForFlowParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) ExecutionExistsForFlow(ctx context.Context, arg ExecutionExistsForFlowParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, executionExistsForFlow, arg.Slug, arg.Uuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllExecutionsPaginated = `-- name: GetAllExecutionsPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $1
),
latest_versions AS (
    SELECT exec_id, MAX(version) as max_version
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
    GROUP BY exec_id
),
filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries, u.name, u.username, u.uuid as triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
           f.name as flow_name,
           f.slug as flow_slug
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    INNER JOIN users u ON el.triggered_by = u.id
    INNER JOIN latest_versions lv ON el.exec_id = lv.exec_id AND el.version = lv.max_version
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.exec_id, p.flow_id, p.version, p.input, p.error, p.current_action_id, p.status, p.trigger_type, p.triggered_by, p.namespace_id, p.created_at, p.updated_at, p.completed_at, p.action_retries, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type GetAllExecutionsPaginatedParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type GetAllExecutionsPaginatedRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
	PageCount       int64                 `db:"page_count" json:"page_count"`
	TotalCount      int64                 `db:"total_count" json:"total_count"`
}

func (q *Queries) GetAllExecutionsPaginated(ctx context.Context, arg GetAllExecutionsPaginatedParams) ([]GetAllExecutionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllExecutionsPaginated, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllExecutionsPaginatedRow
	for rows.Next() {
		var i GetAllExecutionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.Version,
			&i.Input,
			&i.Error,
			&i.CurrentActionID,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ActionRetries,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionActionRetries = `-- name: GetExecutionActionRetries :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log el
    WHERE el.exec_id = $1 AND el.namespace_id = (SELECT id FROM namespace_lookup)
)
SELECT el.action_retries FROM execution_log el
WHERE el.exec_id = $1
  AND el.version = (SELECT version FROM latest_version)
  AND el.namespace_id = (SELECT id FROM namespace_lookup)
`

type GetExecutionActionRetriesParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetExecutionActionRetries(ctx context.Context, arg GetExecutionActionRetriesParams) (pqtype.NullRawMessage, error) {
	row := q.db.QueryRowContext(ctx, getExecutionActionRetries, arg.ExecID, arg.Uuid)
	var action_retries pqtype.NullRawMessage
	err := row.Scan(&action_retries)
	return action_retries, err
}

const getExecutionByExecID = `-- name: GetExecutionByExecID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log
    WHERE exec_id = $1 AND namespace_id = (SELECT id FROM namespace_lookup)
)
SELECT
    el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries,
    u.name,
    u.username,
    u.uuid AS triggered_by_uuid,
    CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
    f.name as flow_name,
    f.slug as flow_slug
FROM
    execution_log el
INNER JOIN
    users u ON el.triggered_by = u.id
INNER JOIN
    flows f ON el.flow_id = f.id
WHERE
    el.exec_id = $1
    AND el.version = (SELECT version FROM latest_version)
    AND el.namespace_id = (SELECT id FROM namespace_lookup)
    AND f.is_active = TRUE
`

type GetExecutionByExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByExecID(ctx context.Context, arg GetExecutionByExecIDParams) (GetExecutionByExecIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecID, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionByExecIDWithNamespace = `-- name: GetExecutionByExecIDWithNamespace :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log el2
    INNER JOIN flows f2 ON el2.flow_id = f2.id
    WHERE el2.exec_id = $1 AND f2.namespace_id = (SELECT id FROM namespace_lookup) AND f2.is_active = TRUE
)
SELECT
    el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries,
    u.name,
    u.username,
    u.uuid AS triggered_by_uuid,
    CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
    f.name as flow_name,
    f.slug as flow_slug
FROM
    execution_log el
INNER JOIN
    users u ON el.triggered_by = u.id
INNER JOIN
    flows f ON el.flow_id = f.id
WHERE
    el.exec_id = $1
    AND el.version = (SELECT version FROM latest_version)
    AND f.namespace_id = (SELECT id FROM namespace_lookup)
    AND f.is_active = TRUE
`

type GetExecutionByExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByExecIDWithNamespaceRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByExecIDWithNamespace(ctx context.Context, arg GetExecutionByExecIDWithNamespaceParams) (GetExecutionByExecIDWithNamespaceRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i GetExecutionByExecIDWithNamespaceRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
)
SELECT el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries, u.name, u.username, u.uuid as triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
       f.name as flow_name,
       f.slug as flow_slug
FROM execution_log el
INNER JOIN users u ON el.triggered_by = u.id
INNER JOIN flows f ON el.flow_id = f.id
WHERE el.id = $1 AND el.namespace_id = (SELECT id FROM namespace_lookup) AND f.is_active = TRUE
`

type GetExecutionByIDParams struct {
	ID   int32     `db:"id" json:"id"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

type GetExecutionByIDRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (GetExecutionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByID, arg.ID, arg.Uuid)
	var i GetExecutionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
		&i.Name,
		&i.Username,
		&i.TriggeredByUuid,
		&i.TriggeredByName,
		&i.FlowName,
		&i.FlowSlug,
	)
	return i, err
}

const getExecutionsByFlow = `-- name: GetExecutionsByFlow :many
WITH user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $2
), namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
)
SELECT el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries, u.name, u.username, u.uuid as triggered_by_uuid,
       CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
       f.name as flow_name,
       f.slug as flow_slug
FROM execution_log el
INNER JOIN flows f ON el.flow_id = f.id
INNER JOIN users u ON el.triggered_by = u.id
WHERE f.id = $1
  AND el.triggered_by = (SELECT id FROM user_lookup)
  AND f.namespace_id = (SELECT id FROM namespace_lookup)
  AND f.is_active = TRUE
`

type GetExecutionsByFlowParams struct {
	ID     int32     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetExecutionsByFlowRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
}

func (q *Queries) GetExecutionsByFlow(ctx context.Context, arg GetExecutionsByFlowParams) ([]GetExecutionsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlow, arg.ID, arg.Uuid, arg.Uuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExecutionsByFlowRow
	for rows.Next() {
		var i GetExecutionsByFlowRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.Version,
			&i.Input,
			&i.Error,
			&i.CurrentActionID,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ActionRetries,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionsByFlowPaginated = `-- name: GetExecutionsByFlowPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
),
latest_versions AS (
    SELECT exec_id, MAX(version) as max_version
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    WHERE f.id = $1
      AND f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
    GROUP BY exec_id
),
filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries, u.name, u.username, u.uuid as triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
           f.name as flow_name,
           f.slug as flow_slug
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    INNER JOIN users u ON el.triggered_by = u.id
    INNER JOIN latest_versions lv ON el.exec_id = lv.exec_id AND el.version = lv.max_version
    WHERE f.id = $1
      AND f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered
    ORDER BY created_at DESC
    LIMIT $3 OFFSET $4
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.exec_id, p.flow_id, p.version, p.input, p.error, p.current_action_id, p.status, p.trigger_type, p.triggered_by, p.namespace_id, p.created_at, p.updated_at, p.completed_at, p.action_retries, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type GetExecutionsByFlowPaginatedParams struct {
	ID     int32     `db:"id" json:"id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type GetExecutionsByFlowPaginatedRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
	PageCount       int64                 `db:"page_count" json:"page_count"`
	TotalCount      int64                 `db:"total_count" json:"total_count"`
}

func (q *Queries) GetExecutionsByFlowPaginated(ctx context.Context, arg GetExecutionsByFlowPaginatedParams) ([]GetExecutionsByFlowPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlowPaginated,
		arg.ID,
		arg.Uuid,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExecutionsByFlowPaginatedRow
	for rows.Next() {
		var i GetExecutionsByFlowPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.Version,
			&i.Input,
			&i.Error,
			&i.CurrentActionID,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ActionRetries,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowFromExecID = `-- name: GetFlowFromExecID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_exec_log AS (
    SELECT flow_id
    FROM execution_log
    WHERE exec_id = $1
    ORDER BY version DESC
    LIMIT 1
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at FROM flows f
INNER JOIN latest_exec_log el ON el.flow_id = f.id
WHERE f.namespace_id = (SELECT id FROM namespace_lookup) AND f.is_active = TRUE
`

type GetFlowFromExecIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecID(ctx context.Context, arg GetFlowFromExecIDParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecID, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowFromExecIDWithNamespace = `-- name: GetFlowFromExecIDWithNamespace :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_exec_log AS (
    SELECT flow_id
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    WHERE el.exec_id = $1
      AND f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
    ORDER BY el.version DESC
    LIMIT 1
)
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at FROM flows f
INNER JOIN latest_exec_log el ON el.flow_id = f.id
WHERE f.namespace_id = (SELECT id FROM namespace_lookup) AND f.is_active = TRUE
`

type GetFlowFromExecIDWithNamespaceParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowFromExecIDWithNamespace(ctx context.Context, arg GetFlowFromExecIDWithNamespaceParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecIDWithNamespace, arg.ExecID, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInputForExecByUUID = `-- name: GetInputForExecByUUID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $2
), latest_execution AS (
    SELECT MAX(version) as max_version
    FROM execution_log
    WHERE exec_id = $1 AND namespace_id = (SELECT id FROM namespace_lookup)
)
SELECT input FROM execution_log
WHERE execution_log.exec_id = $1
  AND execution_log.namespace_id = (SELECT id FROM namespace_lookup)
  AND execution_log.version = (SELECT max_version FROM latest_execution)
`

type GetInputForExecByUUIDParams struct {
	ExecID string    `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetInputForExecByUUID(ctx context.Context, arg GetInputForExecByUUIDParams) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getInputForExecByUUID, arg.ExecID, arg.Uuid)
	var input json.RawMessage
	err := row.Scan(&input)
	return input, err
}

const incrementActionRetry = `-- name: IncrementActionRetry :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log el
    WHERE el.exec_id = $1 AND el.namespace_id = (SELECT id FROM namespace_lookup)
)
UPDATE execution_log el
SET
    action_retries = jsonb_set(
        COALESCE(action_retries, '{}'::jsonb),
        ARRAY[$2],
        to_jsonb((COALESCE(action_retries->>$2, '0')::int + 1))
    ),
    updated_at = NOW()
WHERE el.exec_id = $1
  AND el.version = (SELECT version FROM latest_version)
  AND el.namespace_id = (SELECT id FROM namespace_lookup)
RETURNING
    action_retries,
    (action_retries->>$2)::int as retry_count
`

type IncrementActionRetryParams struct {
	ExecID  string      `db:"exec_id" json:"exec_id"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Uuid    uuid.UUID   `db:"uuid" json:"uuid"`
}

type IncrementActionRetryRow struct {
	ActionRetries pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	RetryCount    int32                 `db:"retry_count" json:"retry_count"`
}

func (q *Queries) IncrementActionRetry(ctx context.Context, arg IncrementActionRetryParams) (IncrementActionRetryRow, error) {
	row := q.db.QueryRowContext(ctx, incrementActionRetry, arg.ExecID, arg.Column2, arg.Uuid)
	var i IncrementActionRetryRow
	err := row.Scan(&i.ActionRetries, &i.RetryCount)
	return i, err
}

const searchExecutionsPaginated = `-- name: SearchExecutionsPaginated :many
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $1
),
latest_versions AS (
    SELECT exec_id, MAX(version) as max_version
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
    GROUP BY exec_id
),
filtered AS (
    SELECT el.id, el.exec_id, el.flow_id, el.version, el.input, el.error, el.current_action_id, el.status, el.trigger_type, el.triggered_by, el.namespace_id, el.created_at, el.updated_at, el.completed_at, el.action_retries, u.name, u.username, u.uuid as triggered_by_uuid,
           CONCAT(u.name, ' <', u.username, '>')::TEXT as triggered_by_name,
           f.name as flow_name,
           f.slug as flow_slug
    FROM execution_log el
    INNER JOIN flows f ON el.flow_id = f.id
    INNER JOIN users u ON el.triggered_by = u.id
    INNER JOIN latest_versions lv ON el.exec_id = lv.exec_id AND el.version = lv.max_version
    WHERE f.namespace_id = (SELECT id FROM namespace_lookup)
      AND f.is_active = TRUE
      AND (
        $2 = '' OR
        f.name ILIKE '%' || $2 || '%' OR
        f.slug ILIKE '%' || $2 || '%' OR
        el.exec_id ILIKE '%' || $2 || '%' OR
        u.name ILIKE '%' || $2 || '%' OR
        u.username ILIKE '%' || $2 || '%'
      )
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries, name, username, triggered_by_uuid, triggered_by_name, flow_name, flow_slug FROM filtered
    ORDER BY created_at DESC
    LIMIT $3 OFFSET $4
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.exec_id, p.flow_id, p.version, p.input, p.error, p.current_action_id, p.status, p.trigger_type, p.triggered_by, p.namespace_id, p.created_at, p.updated_at, p.completed_at, p.action_retries, p.name, p.username, p.triggered_by_uuid, p.triggered_by_name, p.flow_name, p.flow_slug,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchExecutionsPaginatedParams struct {
	Uuid    uuid.UUID   `db:"uuid" json:"uuid"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type SearchExecutionsPaginatedRow struct {
	ID              int32                 `db:"id" json:"id"`
	ExecID          string                `db:"exec_id" json:"exec_id"`
	FlowID          int32                 `db:"flow_id" json:"flow_id"`
	Version         int32                 `db:"version" json:"version"`
	Input           json.RawMessage       `db:"input" json:"input"`
	Error           sql.NullString        `db:"error" json:"error"`
	CurrentActionID sql.NullString        `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus       `db:"status" json:"status"`
	TriggerType     TriggerType           `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32                 `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32                 `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time             `db:"updated_at" json:"updated_at"`
	CompletedAt     sql.NullTime          `db:"completed_at" json:"completed_at"`
	ActionRetries   pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Name            string                `db:"name" json:"name"`
	Username        string                `db:"username" json:"username"`
	TriggeredByUuid uuid.UUID             `db:"triggered_by_uuid" json:"triggered_by_uuid"`
	TriggeredByName string                `db:"triggered_by_name" json:"triggered_by_name"`
	FlowName        string                `db:"flow_name" json:"flow_name"`
	FlowSlug        string                `db:"flow_slug" json:"flow_slug"`
	PageCount       int64                 `db:"page_count" json:"page_count"`
	TotalCount      int64                 `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchExecutionsPaginated(ctx context.Context, arg SearchExecutionsPaginatedParams) ([]SearchExecutionsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchExecutionsPaginated,
		arg.Uuid,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchExecutionsPaginatedRow
	for rows.Next() {
		var i SearchExecutionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.Version,
			&i.Input,
			&i.Error,
			&i.CurrentActionID,
			&i.Status,
			&i.TriggerType,
			&i.TriggeredBy,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.ActionRetries,
			&i.Name,
			&i.Username,
			&i.TriggeredByUuid,
			&i.TriggeredByName,
			&i.FlowName,
			&i.FlowSlug,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionActionID = `-- name: UpdateExecutionActionID :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log
    WHERE execution_log.exec_id = $2 AND namespace_id = (SELECT id FROM namespace_lookup)
)
UPDATE execution_log SET current_action_id=$1, updated_at=NOW()
WHERE execution_log.exec_id = $2
  AND version = (SELECT version FROM latest_version)
  AND namespace_id = (SELECT id FROM namespace_lookup)
RETURNING id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries
`

type UpdateExecutionActionIDParams struct {
	CurrentActionID sql.NullString `db:"current_action_id" json:"current_action_id"`
	ExecID          string         `db:"exec_id" json:"exec_id"`
	Uuid            uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateExecutionActionID(ctx context.Context, arg UpdateExecutionActionIDParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionActionID, arg.CurrentActionID, arg.ExecID, arg.Uuid)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
	)
	return i, err
}

const updateExecutionActionRetries = `-- name: UpdateExecutionActionRetries :exec
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $3
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log el
    WHERE el.exec_id = $1 AND el.namespace_id = (SELECT id FROM namespace_lookup)
)
UPDATE execution_log el
SET action_retries = $2, updated_at = NOW()
WHERE el.exec_id = $1
  AND el.version = (SELECT version FROM latest_version)
  AND el.namespace_id = (SELECT id FROM namespace_lookup)
`

type UpdateExecutionActionRetriesParams struct {
	ExecID        string                `db:"exec_id" json:"exec_id"`
	ActionRetries pqtype.NullRawMessage `db:"action_retries" json:"action_retries"`
	Uuid          uuid.UUID             `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateExecutionActionRetries(ctx context.Context, arg UpdateExecutionActionRetriesParams) error {
	_, err := q.db.ExecContext(ctx, updateExecutionActionRetries, arg.ExecID, arg.ActionRetries, arg.Uuid)
	return err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
WITH namespace_lookup AS (
    SELECT id FROM namespaces WHERE namespaces.uuid = $4
), latest_version AS (
    SELECT MAX(version) as version
    FROM execution_log
    WHERE execution_log.exec_id = $3 AND namespace_id = (SELECT id FROM namespace_lookup)
)
UPDATE execution_log SET
    status=$1,
    error=$2,
    updated_at=NOW(),
    completed_at = CASE WHEN $1 IN ('completed'::execution_status, 'errored'::execution_status, 'cancelled'::execution_status) THEN NOW() ELSE completed_at END
WHERE execution_log.exec_id = $3
  AND version = (SELECT version FROM latest_version)
  AND namespace_id = (SELECT id FROM namespace_lookup)
RETURNING id, exec_id, flow_id, version, input, error, current_action_id, status, trigger_type, triggered_by, namespace_id, created_at, updated_at, completed_at, action_retries
`

type UpdateExecutionStatusParams struct {
	Status ExecutionStatus `db:"status" json:"status"`
	Error  sql.NullString  `db:"error" json:"error"`
	ExecID string          `db:"exec_id" json:"exec_id"`
	Uuid   uuid.UUID       `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.Error,
		arg.ExecID,
		arg.Uuid,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.Version,
		&i.Input,
		&i.Error,
		&i.CurrentActionID,
		&i.Status,
		&i.TriggerType,
		&i.TriggeredBy,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ActionRetries,
	)
	return i, err
}
