// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: execution.sql

package repo

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addExecutionLog = `-- name: AddExecutionLog :one
WITH user_lookup AS (
    SELECT id FROM users WHERE uuid = $5
)
INSERT INTO execution_log (
    exec_id,
    parent_exec_id,
    flow_id,
    input,
    triggered_by
) VALUES (
    $1, $2, $3, $4, (SELECT id FROM user_lookup)
) RETURNING id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, created_at, updated_at
`

type AddExecutionLogParams struct {
	ExecID       string          `db:"exec_id" json:"exec_id"`
	ParentExecID sql.NullString  `db:"parent_exec_id" json:"parent_exec_id"`
	FlowID       int32           `db:"flow_id" json:"flow_id"`
	Input        json.RawMessage `db:"input" json:"input"`
	Uuid         uuid.UUID       `db:"uuid" json:"uuid"`
}

func (q *Queries) AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, addExecutionLog,
		arg.ExecID,
		arg.ParentExecID,
		arg.FlowID,
		arg.Input,
		arg.Uuid,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildrenByParentUUID = `-- name: GetChildrenByParentUUID :many
SELECT id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, created_at, updated_at FROM execution_log WHERE parent_exec_id = $1
`

func (q *Queries) GetChildrenByParentUUID(ctx context.Context, parentExecID sql.NullString) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, getChildrenByParentUUID, parentExecID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.ParentExecID,
			&i.Input,
			&i.Error,
			&i.Status,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionByExecID = `-- name: GetExecutionByExecID :one
SELECT
    el.id, el.exec_id, el.flow_id, el.parent_exec_id, el.input, el.error, el.status, el.triggered_by, el.created_at, el.updated_at,
    u.uuid AS triggered_by_uuid
FROM
    execution_log el
INNER JOIN
    users u ON el.triggered_by = u.id
WHERE
    el.exec_id = $1
`

type GetExecutionByExecIDRow struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	ParentExecID    sql.NullString  `db:"parent_exec_id" json:"parent_exec_id"`
	Input           json.RawMessage `db:"input" json:"input"`
	Error           sql.NullString  `db:"error" json:"error"`
	Status          ExecutionStatus `db:"status" json:"status"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	TriggeredByUuid uuid.UUID       `db:"triggered_by_uuid" json:"triggered_by_uuid"`
}

func (q *Queries) GetExecutionByExecID(ctx context.Context, execID string) (GetExecutionByExecIDRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByExecID, execID)
	var i GetExecutionByExecIDRow
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggeredByUuid,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, created_at, updated_at FROM execution_log WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id int32) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, getExecutionByID, id)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionsByFlow = `-- name: GetExecutionsByFlow :many
WITH user_lookup AS (
    SELECT id FROM users WHERE uuid = $2
)
SELECT id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, created_at, updated_at FROM execution_log WHERE flow_id = $1 and triggered_by = (SELECT id FROM user_lookup)
`

type GetExecutionsByFlowParams struct {
	FlowID int32     `db:"flow_id" json:"flow_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetExecutionsByFlow(ctx context.Context, arg GetExecutionsByFlowParams) ([]ExecutionLog, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByFlow, arg.FlowID, arg.Uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.ExecID,
			&i.FlowID,
			&i.ParentExecID,
			&i.Input,
			&i.Error,
			&i.Status,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowFromExecID = `-- name: GetFlowFromExecID :one
WITH exec_log AS (
    SELECT flow_id FROM execution_log WHERE exec_id = $1
)
SELECT id, slug, name, checksum, description, created_at, updated_at, namespace_id, flow_id FROM flows inner join exec_log on exec_log.flow_id = flows.id
`

type GetFlowFromExecIDRow struct {
	ID          int32          `db:"id" json:"id"`
	Slug        string         `db:"slug" json:"slug"`
	Name        string         `db:"name" json:"name"`
	Checksum    string         `db:"checksum" json:"checksum"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceID int32          `db:"namespace_id" json:"namespace_id"`
	FlowID      int32          `db:"flow_id" json:"flow_id"`
}

func (q *Queries) GetFlowFromExecID(ctx context.Context, execID string) (GetFlowFromExecIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFlowFromExecID, execID)
	var i GetFlowFromExecIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceID,
		&i.FlowID,
	)
	return i, err
}

const getInputForExecByUUID = `-- name: GetInputForExecByUUID :one
SELECT input FROM execution_log WHERE exec_id = $1
`

func (q *Queries) GetInputForExecByUUID(ctx context.Context, execID string) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getInputForExecByUUID, execID)
	var input json.RawMessage
	err := row.Scan(&input)
	return input, err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE execution_log SET status=$1, error=$2, updated_at=$3 WHERE exec_id = $4 RETURNING id, exec_id, flow_id, parent_exec_id, input, error, status, triggered_by, created_at, updated_at
`

type UpdateExecutionStatusParams struct {
	Status    ExecutionStatus `db:"status" json:"status"`
	Error     sql.NullString  `db:"error" json:"error"`
	UpdatedAt time.Time       `db:"updated_at" json:"updated_at"`
	ExecID    string          `db:"exec_id" json:"exec_id"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.ExecID,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.ExecID,
		&i.FlowID,
		&i.ParentExecID,
		&i.Input,
		&i.Error,
		&i.Status,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
