// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flows.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (
    slug,
    name,
    description,
    checksum,
    file_path,
    namespace_id,
    prefix_id
) VALUES (
    $1, $2, $3, $4, $5, (SELECT id FROM namespaces WHERE namespaces.name = $6), $7
) RETURNING id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id
`

type CreateFlowParams struct {
	Slug        string         `db:"slug" json:"slug"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	Checksum    string         `db:"checksum" json:"checksum"`
	FilePath    string         `db:"file_path" json:"file_path"`
	Name_2      string         `db:"name_2" json:"name_2"`
	PrefixID    sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, createFlow,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Checksum,
		arg.FilePath,
		arg.Name_2,
		arg.PrefixID,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrefixID,
	)
	return i, err
}

const deleteAllFlows = `-- name: DeleteAllFlows :exec
DELETE FROM flows
`

func (q *Queries) DeleteAllFlows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFlows)
	return err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE slug = $1 AND namespace_id = (SELECT id FROM namespaces where namespaces.uuid = $2)
`

type DeleteFlowParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) DeleteFlow(ctx context.Context, arg DeleteFlowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFlow, arg.Slug, arg.Uuid)
	return err
}

const getDistinctPrefixes = `-- name: GetDistinctPrefixes :many
SELECT DISTINCT fp.uuid, fp.name, fp.description FROM flow_prefixes fp
JOIN flows f ON f.prefix_id = fp.id
JOIN namespaces n ON f.namespace_id = n.id
WHERE n.uuid = $1 AND f.is_active = TRUE
ORDER BY fp.name ASC
`

type GetDistinctPrefixesRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
}

func (q *Queries) GetDistinctPrefixes(ctx context.Context, argUuid uuid.UUID) ([]GetDistinctPrefixesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctPrefixes, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDistinctPrefixesRow
	for rows.Next() {
		var i GetDistinctPrefixesRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowBySlug = `-- name: GetFlowBySlug :one
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE f.slug = $1 AND n.uuid = $2 AND ($3::boolean IS NULL OR f.is_active = $3)
`

type GetFlowBySlugParams struct {
	Slug     string       `db:"slug" json:"slug"`
	Uuid     uuid.UUID    `db:"uuid" json:"uuid"`
	IsActive sql.NullBool `db:"is_active" json:"is_active"`
}

func (q *Queries) GetFlowBySlug(ctx context.Context, arg GetFlowBySlugParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowBySlug, arg.Slug, arg.Uuid, arg.IsActive)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrefixID,
	)
	return i, err
}

const getFlowCountByPrefix = `-- name: GetFlowCountByPrefix :one
SELECT COUNT(*) FROM flows f
WHERE f.prefix_id = $1 AND f.is_active = TRUE
`

func (q *Queries) GetFlowCountByPrefix(ctx context.Context, prefixID sql.NullInt32) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFlowCountByPrefix, prefixID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFlowsByNamespace = `-- name: GetFlowsByNamespace :many
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid
FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE n.uuid = $1 AND f.is_active = TRUE
`

type GetFlowsByNamespaceRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetFlowsByNamespace(ctx context.Context, argUuid uuid.UUID) ([]GetFlowsByNamespaceRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlowsByNamespace, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowsByNamespaceRow
	for rows.Next() {
		var i GetFlowsByNamespaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlowsByPrefix = `-- name: GetFlowsByPrefix :many
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE n.uuid = $1 AND f.prefix_id = $2 AND f.is_active = TRUE
ORDER BY f.name ASC
`

type GetFlowsByPrefixParams struct {
	Uuid     uuid.UUID     `db:"uuid" json:"uuid"`
	PrefixID sql.NullInt32 `db:"prefix_id" json:"prefix_id"`
}

type GetFlowsByPrefixRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetFlowsByPrefix(ctx context.Context, arg GetFlowsByPrefixParams) ([]GetFlowsByPrefixRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlowsByPrefix, arg.Uuid, arg.PrefixID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowsByPrefixRow
	for rows.Next() {
		var i GetFlowsByPrefixRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledFlows = `-- name: GetScheduledFlows :many
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid, cs.id AS schedule_id, cs.cron, cs.timezone, cs.inputs, cs.created_by, cs.is_user_created
FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
JOIN cron_schedules cs ON cs.flow_id = f.id
WHERE f.is_active = TRUE AND cs.is_active = TRUE
`

type GetScheduledFlowsRow struct {
	ID            int32                 `db:"id" json:"id"`
	Slug          string                `db:"slug" json:"slug"`
	Name          string                `db:"name" json:"name"`
	Checksum      string                `db:"checksum" json:"checksum"`
	Description   sql.NullString        `db:"description" json:"description"`
	FilePath      string                `db:"file_path" json:"file_path"`
	NamespaceID   int32                 `db:"namespace_id" json:"namespace_id"`
	IsActive      bool                  `db:"is_active" json:"is_active"`
	CreatedAt     time.Time             `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time             `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32         `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID             `db:"namespace_uuid" json:"namespace_uuid"`
	ScheduleID    int32                 `db:"schedule_id" json:"schedule_id"`
	Cron          string                `db:"cron" json:"cron"`
	Timezone      string                `db:"timezone" json:"timezone"`
	Inputs        pqtype.NullRawMessage `db:"inputs" json:"inputs"`
	CreatedBy     int32                 `db:"created_by" json:"created_by"`
	IsUserCreated bool                  `db:"is_user_created" json:"is_user_created"`
}

func (q *Queries) GetScheduledFlows(ctx context.Context) ([]GetScheduledFlowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduledFlowsRow
	for rows.Next() {
		var i GetScheduledFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.ScheduleID,
			&i.Cron,
			&i.Timezone,
			&i.Inputs,
			&i.CreatedBy,
			&i.IsUserCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    WHERE n.uuid = $1
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id, namespace_uuid FROM filtered
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.file_path, p.namespace_id, p.is_active, p.created_at, p.updated_at, p.prefix_id, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListFlowsParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListFlowsRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListFlows(ctx context.Context, arg ListFlowsParams) ([]ListFlowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlows, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsRow
	for rows.Next() {
		var i ListFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsPaginated = `-- name: ListFlowsPaginated :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid,
           fp.name AS prefix_name
    FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    LEFT JOIN flow_prefixes fp ON f.prefix_id = fp.id
    WHERE n.uuid = $1 AND f.is_active = TRUE
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id, namespace_uuid, prefix_name FROM filtered
    ORDER BY
        CASE WHEN prefix_id IS NULL THEN 1 ELSE 0 END ASC,
        prefix_name ASC NULLS LAST,
        name ASC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.file_path, p.namespace_id, p.is_active, p.created_at, p.updated_at, p.prefix_id, p.namespace_uuid, p.prefix_name,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListFlowsPaginatedParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListFlowsPaginatedRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PrefixName    sql.NullString `db:"prefix_name" json:"prefix_name"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListFlowsPaginated(ctx context.Context, arg ListFlowsPaginatedParams) ([]ListFlowsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsPaginated, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsPaginatedRow
	for rows.Next() {
		var i ListFlowsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.PrefixName,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsPaginatedFiltered = `-- name: ListFlowsPaginatedFiltered :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid,
           fp.name AS prefix_name
    FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    LEFT JOIN flow_prefixes fp ON f.prefix_id = fp.id
    WHERE n.uuid = $1 AND f.is_active = TRUE
      AND (f.prefix_id IS NULL OR fp.name = ANY($4::text[]))
),
total AS (SELECT COUNT(*) AS total_count FROM filtered),
paged AS (
    SELECT id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id, namespace_uuid, prefix_name FROM filtered
    ORDER BY
        CASE WHEN prefix_id IS NULL THEN 1 ELSE 0 END ASC,
        prefix_name ASC NULLS LAST,
        name ASC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT p.id, p.slug, p.name, p.checksum, p.description, p.file_path, p.namespace_id, p.is_active, p.created_at, p.updated_at, p.prefix_id, p.namespace_uuid, p.prefix_name, pc.page_count, t.total_count FROM paged p, page_count pc, total t
`

type ListFlowsPaginatedFilteredParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column4 []string  `db:"column_4" json:"column_4"`
}

type ListFlowsPaginatedFilteredRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PrefixName    sql.NullString `db:"prefix_name" json:"prefix_name"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListFlowsPaginatedFiltered(ctx context.Context, arg ListFlowsPaginatedFilteredParams) ([]ListFlowsPaginatedFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsPaginatedFiltered,
		arg.Uuid,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.Column4),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsPaginatedFilteredRow
	for rows.Next() {
		var i ListFlowsPaginatedFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.PrefixName,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllFlowsInactiveForNamespace = `-- name: MarkAllFlowsInactiveForNamespace :exec
UPDATE flows SET is_active = FALSE, updated_at = NOW()
WHERE namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
`

func (q *Queries) MarkAllFlowsInactiveForNamespace(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllFlowsInactiveForNamespace, argUuid)
	return err
}

const markFlowActive = `-- name: MarkFlowActive :exec
UPDATE flows SET is_active = TRUE, updated_at = NOW()
WHERE slug = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type MarkFlowActiveParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) MarkFlowActive(ctx context.Context, arg MarkFlowActiveParams) error {
	_, err := q.db.ExecContext(ctx, markFlowActive, arg.Slug, arg.Uuid)
	return err
}

const searchFlowsPaginated = `-- name: SearchFlowsPaginated :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid,
           fp.name AS prefix_name
    FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    LEFT JOIN flow_prefixes fp ON f.prefix_id = fp.id
    WHERE n.uuid = $1
      AND f.is_active = TRUE
      AND (lower(f.name) LIKE '%' || lower($2::text) || '%'
           OR lower(f.description) LIKE '%' || lower($2::text) || '%')
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id, namespace_uuid, prefix_name FROM filtered
    ORDER BY
        CASE WHEN prefix_id IS NULL THEN 1 ELSE 0 END ASC,
        prefix_name ASC NULLS LAST,
        name ASC
    LIMIT $3 OFFSET $4
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.file_path, p.namespace_id, p.is_active, p.created_at, p.updated_at, p.prefix_id, p.namespace_uuid, p.prefix_name,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchFlowsPaginatedParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Column2 string    `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type SearchFlowsPaginatedRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PrefixName    sql.NullString `db:"prefix_name" json:"prefix_name"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchFlowsPaginated(ctx context.Context, arg SearchFlowsPaginatedParams) ([]SearchFlowsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFlowsPaginated,
		arg.Uuid,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFlowsPaginatedRow
	for rows.Next() {
		var i SearchFlowsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.PrefixName,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFlowsPaginatedFiltered = `-- name: SearchFlowsPaginatedFiltered :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.file_path, f.namespace_id, f.is_active, f.created_at, f.updated_at, f.prefix_id, n.uuid AS namespace_uuid,
           fp.name AS prefix_name
    FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    LEFT JOIN flow_prefixes fp ON f.prefix_id = fp.id
    WHERE n.uuid = $1
      AND f.is_active = TRUE
      AND (lower(f.name) LIKE '%' || lower($2::text) || '%'
           OR lower(f.description) LIKE '%' || lower($2::text) || '%')
      AND (f.prefix_id IS NULL OR fp.name = ANY($5::text[]))
),
total AS (SELECT COUNT(*) AS total_count FROM filtered),
paged AS (
    SELECT id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id, namespace_uuid, prefix_name FROM filtered
    ORDER BY
        CASE WHEN prefix_id IS NULL THEN 1 ELSE 0 END ASC,
        prefix_name ASC NULLS LAST,
        name ASC
    LIMIT $3 OFFSET $4
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT p.id, p.slug, p.name, p.checksum, p.description, p.file_path, p.namespace_id, p.is_active, p.created_at, p.updated_at, p.prefix_id, p.namespace_uuid, p.prefix_name, pc.page_count, t.total_count FROM paged p, page_count pc, total t
`

type SearchFlowsPaginatedFilteredParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Column2 string    `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column5 []string  `db:"column_5" json:"column_5"`
}

type SearchFlowsPaginatedFilteredRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	IsActive      bool           `db:"is_active" json:"is_active"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	PrefixID      sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PrefixName    sql.NullString `db:"prefix_name" json:"prefix_name"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchFlowsPaginatedFiltered(ctx context.Context, arg SearchFlowsPaginatedFilteredParams) ([]SearchFlowsPaginatedFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFlowsPaginatedFiltered,
		arg.Uuid,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		pq.Array(arg.Column5),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFlowsPaginatedFilteredRow
	for rows.Next() {
		var i SearchFlowsPaginatedFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			&i.FilePath,
			&i.NamespaceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PrefixID,
			&i.NamespaceUuid,
			&i.PrefixName,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :one
UPDATE flows SET
    name = $1,
    description = $2,
    checksum = $3,
    file_path = $4,
    prefix_id = $5,
    is_active = TRUE,
    updated_at = NOW()
WHERE slug = $6 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.name = $7)
RETURNING id, slug, name, checksum, description, file_path, namespace_id, is_active, created_at, updated_at, prefix_id
`

type UpdateFlowParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	Checksum    string         `db:"checksum" json:"checksum"`
	FilePath    string         `db:"file_path" json:"file_path"`
	PrefixID    sql.NullInt32  `db:"prefix_id" json:"prefix_id"`
	Slug        string         `db:"slug" json:"slug"`
	Name_2      string         `db:"name_2" json:"name_2"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, updateFlow,
		arg.Name,
		arg.Description,
		arg.Checksum,
		arg.FilePath,
		arg.PrefixID,
		arg.Slug,
		arg.Name_2,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		&i.FilePath,
		&i.NamespaceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrefixID,
	)
	return i, err
}
