// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flow_prefixes.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createFlowPrefix = `-- name: CreateFlowPrefix :one
INSERT INTO flow_prefixes (namespace_id, name, description)
VALUES ((SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1), $2, $3)
RETURNING id, uuid, namespace_id, name, description, created_at, updated_at
`

type CreateFlowPrefixParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
}

func (q *Queries) CreateFlowPrefix(ctx context.Context, arg CreateFlowPrefixParams) (FlowPrefix, error) {
	row := q.db.QueryRowContext(ctx, createFlowPrefix, arg.Uuid, arg.Name, arg.Description)
	var i FlowPrefix
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowPrefix = `-- name: DeleteFlowPrefix :exec
DELETE FROM flow_prefixes
WHERE flow_prefixes.uuid = $1
AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteFlowPrefixParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteFlowPrefix(ctx context.Context, arg DeleteFlowPrefixParams) error {
	_, err := q.db.ExecContext(ctx, deleteFlowPrefix, arg.Uuid, arg.Uuid_2)
	return err
}

const getFlowPrefixByName = `-- name: GetFlowPrefixByName :one
SELECT fp.id, fp.uuid, fp.namespace_id, fp.name, fp.description, fp.created_at, fp.updated_at FROM flow_prefixes fp
WHERE fp.name = $1
AND fp.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
`

type GetFlowPrefixByNameParams struct {
	Name string    `db:"name" json:"name"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowPrefixByName(ctx context.Context, arg GetFlowPrefixByNameParams) (FlowPrefix, error) {
	row := q.db.QueryRowContext(ctx, getFlowPrefixByName, arg.Name, arg.Uuid)
	var i FlowPrefix
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowPrefixByUUID = `-- name: GetFlowPrefixByUUID :one
SELECT fp.id, fp.uuid, fp.namespace_id, fp.name, fp.description, fp.created_at, fp.updated_at FROM flow_prefixes fp
WHERE fp.uuid = $1
AND fp.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
`

type GetFlowPrefixByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) GetFlowPrefixByUUID(ctx context.Context, arg GetFlowPrefixByUUIDParams) (FlowPrefix, error) {
	row := q.db.QueryRowContext(ctx, getFlowPrefixByUUID, arg.Uuid, arg.Uuid_2)
	var i FlowPrefix
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlowPrefixes = `-- name: ListFlowPrefixes :many
SELECT fp.id, fp.uuid, fp.namespace_id, fp.name, fp.description, fp.created_at, fp.updated_at FROM flow_prefixes fp
WHERE fp.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1)
ORDER BY fp.name ASC
`

func (q *Queries) ListFlowPrefixes(ctx context.Context, argUuid uuid.UUID) ([]FlowPrefix, error) {
	rows, err := q.db.QueryContext(ctx, listFlowPrefixes, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowPrefix
	for rows.Next() {
		var i FlowPrefix
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.NamespaceID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowPrefix = `-- name: UpdateFlowPrefix :one
UPDATE flow_prefixes SET
    name = $3,
    description = $4,
    updated_at = NOW()
WHERE flow_prefixes.uuid = $1
AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
RETURNING id, uuid, namespace_id, name, description, created_at, updated_at
`

type UpdateFlowPrefixParams struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2      uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
}

func (q *Queries) UpdateFlowPrefix(ctx context.Context, arg UpdateFlowPrefixParams) (FlowPrefix, error) {
	row := q.db.QueryRowContext(ctx, updateFlowPrefix,
		arg.Uuid,
		arg.Uuid_2,
		arg.Name,
		arg.Description,
	)
	var i FlowPrefix
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.NamespaceID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
