// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flow_secrets.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFlowSecret = `-- name: CreateFlowSecret :one
INSERT INTO flow_secrets (flow_id, key, encrypted_value, description, namespace_id)
VALUES ($1, $2, $3, $4, (SELECT id FROM namespaces WHERE namespaces.uuid = $5))
RETURNING id, uuid, flow_id, key, encrypted_value, description, namespace_id, created_at, updated_at
`

type CreateFlowSecretParams struct {
	FlowID         int32          `db:"flow_id" json:"flow_id"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) CreateFlowSecret(ctx context.Context, arg CreateFlowSecretParams) (FlowSecret, error) {
	row := q.db.QueryRowContext(ctx, createFlowSecret,
		arg.FlowID,
		arg.Key,
		arg.EncryptedValue,
		arg.Description,
		arg.Uuid,
	)
	var i FlowSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FlowID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlowSecret = `-- name: DeleteFlowSecret :exec
DELETE FROM flow_secrets
WHERE flow_secrets.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteFlowSecretParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteFlowSecret(ctx context.Context, arg DeleteFlowSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteFlowSecret, arg.Uuid, arg.Uuid_2)
	return err
}

const getFlowSecretByUUID = `-- name: GetFlowSecretByUUID :one
SELECT fs.id, fs.uuid, fs.flow_id, fs.key, fs.encrypted_value, fs.description, fs.namespace_id, fs.created_at, fs.updated_at, ns.uuid AS namespace_uuid FROM flow_secrets fs
JOIN namespaces ns ON fs.namespace_id = ns.id
WHERE fs.uuid = $1 AND ns.uuid = $2
`

type GetFlowSecretByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetFlowSecretByUUIDRow struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	FlowID         int32          `db:"flow_id" json:"flow_id"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	NamespaceID    int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetFlowSecretByUUID(ctx context.Context, arg GetFlowSecretByUUIDParams) (GetFlowSecretByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getFlowSecretByUUID, arg.Uuid, arg.Uuid_2)
	var i GetFlowSecretByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FlowID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const listFlowSecrets = `-- name: ListFlowSecrets :many
SELECT fs.id, fs.uuid, fs.flow_id, fs.key, fs.encrypted_value, fs.description, fs.namespace_id, fs.created_at, fs.updated_at, ns.uuid AS namespace_uuid FROM flow_secrets fs
JOIN namespaces ns ON fs.namespace_id = ns.id
WHERE fs.flow_id = $1 AND ns.uuid = $2
ORDER BY fs.created_at DESC
`

type ListFlowSecretsParams struct {
	FlowID int32     `db:"flow_id" json:"flow_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

type ListFlowSecretsRow struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	FlowID         int32          `db:"flow_id" json:"flow_id"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	NamespaceID    int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) ListFlowSecrets(ctx context.Context, arg ListFlowSecretsParams) ([]ListFlowSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowSecrets, arg.FlowID, arg.Uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowSecretsRow
	for rows.Next() {
		var i ListFlowSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.FlowID,
			&i.Key,
			&i.EncryptedValue,
			&i.Description,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowSecret = `-- name: UpdateFlowSecret :one
UPDATE flow_secrets SET
    encrypted_value = $3,
    description = $4,
    updated_at = NOW()
WHERE flow_secrets.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
RETURNING id, uuid, flow_id, key, encrypted_value, description, namespace_id, created_at, updated_at
`

type UpdateFlowSecretParams struct {
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Uuid_2         uuid.UUID      `db:"uuid_2" json:"uuid_2"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
}

func (q *Queries) UpdateFlowSecret(ctx context.Context, arg UpdateFlowSecretParams) (FlowSecret, error) {
	row := q.db.QueryRowContext(ctx, updateFlowSecret,
		arg.Uuid,
		arg.Uuid_2,
		arg.EncryptedValue,
		arg.Description,
	)
	var i FlowSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.FlowID,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
