// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: flows.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (
    slug,
    name,
    description,
    checksum,
    cron_schedules,
    file_path,
    namespace_id
) VALUES (
    $1, $2, $3, $4, $5, $6, (SELECT id FROM namespaces WHERE namespaces.name = $7)
) RETURNING id, slug, name, checksum, description, cron_schedules, file_path, namespace_id, created_at, updated_at
`

type CreateFlowParams struct {
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Description   sql.NullString `db:"description" json:"description"`
	Checksum      string         `db:"checksum" json:"checksum"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	Name_2        string         `db:"name_2" json:"name_2"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, createFlow,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Checksum,
		pq.Array(arg.CronSchedules),
		arg.FilePath,
		arg.Name_2,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		pq.Array(&i.CronSchedules),
		&i.FilePath,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllFlows = `-- name: DeleteAllFlows :exec
DELETE FROM flows
`

func (q *Queries) DeleteAllFlows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFlows)
	return err
}

const deleteFlow = `-- name: DeleteFlow :exec
DELETE FROM flows WHERE slug = $1 AND namespace_id = (SELECT id FROM namespaces where namespaces.uuid = $2)
`

type DeleteFlowParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) DeleteFlow(ctx context.Context, arg DeleteFlowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFlow, arg.Slug, arg.Uuid)
	return err
}

const getFlowBySlug = `-- name: GetFlowBySlug :one
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE f.slug = $1 AND n.uuid = $2
`

type GetFlowBySlugParams struct {
	Slug string    `db:"slug" json:"slug"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) GetFlowBySlug(ctx context.Context, arg GetFlowBySlugParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, getFlowBySlug, arg.Slug, arg.Uuid)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		pq.Array(&i.CronSchedules),
		&i.FilePath,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlowsByNamespace = `-- name: GetFlowsByNamespace :many
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at, n.uuid AS namespace_uuid
FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE n.uuid = $1
`

type GetFlowsByNamespaceRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetFlowsByNamespace(ctx context.Context, argUuid uuid.UUID) ([]GetFlowsByNamespaceRow, error) {
	rows, err := q.db.QueryContext(ctx, getFlowsByNamespace, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlowsByNamespaceRow
	for rows.Next() {
		var i GetFlowsByNamespaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			pq.Array(&i.CronSchedules),
			&i.FilePath,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledFlows = `-- name: GetScheduledFlows :many
SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at, n.uuid AS namespace_uuid
FROM flows f
JOIN namespaces n ON f.namespace_id = n.id
WHERE f.cron_schedules IS NOT NULL AND array_length(f.cron_schedules, 1) > 0
`

type GetScheduledFlowsRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetScheduledFlows(ctx context.Context) ([]GetScheduledFlowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduledFlowsRow
	for rows.Next() {
		var i GetScheduledFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			pq.Array(&i.CronSchedules),
			&i.FilePath,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlows = `-- name: ListFlows :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at, n.uuid AS namespace_uuid FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    WHERE n.uuid = $1
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, cron_schedules, file_path, namespace_id, created_at, updated_at, namespace_uuid FROM filtered
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.cron_schedules, p.file_path, p.namespace_id, p.created_at, p.updated_at, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListFlowsParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListFlowsRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListFlows(ctx context.Context, arg ListFlowsParams) ([]ListFlowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlows, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsRow
	for rows.Next() {
		var i ListFlowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			pq.Array(&i.CronSchedules),
			&i.FilePath,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlowsPaginated = `-- name: ListFlowsPaginated :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at, n.uuid AS namespace_uuid FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    WHERE n.uuid = $1
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, cron_schedules, file_path, namespace_id, created_at, updated_at, namespace_uuid FROM filtered
    ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.cron_schedules, p.file_path, p.namespace_id, p.created_at, p.updated_at, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListFlowsPaginatedParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListFlowsPaginatedRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) ListFlowsPaginated(ctx context.Context, arg ListFlowsPaginatedParams) ([]ListFlowsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, listFlowsPaginated, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFlowsPaginatedRow
	for rows.Next() {
		var i ListFlowsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			pq.Array(&i.CronSchedules),
			&i.FilePath,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFlowsPaginated = `-- name: SearchFlowsPaginated :many
WITH filtered AS (
    SELECT f.id, f.slug, f.name, f.checksum, f.description, f.cron_schedules, f.file_path, f.namespace_id, f.created_at, f.updated_at, n.uuid AS namespace_uuid FROM flows f
    JOIN namespaces n ON f.namespace_id = n.id
    WHERE n.uuid = $1
      AND (lower(f.name) LIKE '%' || lower($2::text) || '%'
           OR lower(f.description) LIKE '%' || lower($2::text) || '%')
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, slug, name, checksum, description, cron_schedules, file_path, namespace_id, created_at, updated_at, namespace_uuid FROM filtered
    ORDER BY created_at DESC
    LIMIT $3 OFFSET $4
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $3::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.slug, p.name, p.checksum, p.description, p.cron_schedules, p.file_path, p.namespace_id, p.created_at, p.updated_at, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchFlowsPaginatedParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Column2 string    `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

type SearchFlowsPaginatedRow struct {
	ID            int32          `db:"id" json:"id"`
	Slug          string         `db:"slug" json:"slug"`
	Name          string         `db:"name" json:"name"`
	Checksum      string         `db:"checksum" json:"checksum"`
	Description   sql.NullString `db:"description" json:"description"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	NamespaceID   int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount     int64          `db:"page_count" json:"page_count"`
	TotalCount    int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchFlowsPaginated(ctx context.Context, arg SearchFlowsPaginatedParams) ([]SearchFlowsPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFlowsPaginated,
		arg.Uuid,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFlowsPaginatedRow
	for rows.Next() {
		var i SearchFlowsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Checksum,
			&i.Description,
			pq.Array(&i.CronSchedules),
			&i.FilePath,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :one
UPDATE flows SET
    name = $1,
    description = $2,
    checksum = $3,
    cron_schedules = $4,
    file_path = $5,
    updated_at = NOW()
WHERE slug = $6 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.name = $7)
RETURNING id, slug, name, checksum, description, cron_schedules, file_path, namespace_id, created_at, updated_at
`

type UpdateFlowParams struct {
	Name          string         `db:"name" json:"name"`
	Description   sql.NullString `db:"description" json:"description"`
	Checksum      string         `db:"checksum" json:"checksum"`
	CronSchedules []string       `db:"cron_schedules" json:"cron_schedules"`
	FilePath      string         `db:"file_path" json:"file_path"`
	Slug          string         `db:"slug" json:"slug"`
	Name_2        string         `db:"name_2" json:"name_2"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error) {
	row := q.db.QueryRowContext(ctx, updateFlow,
		arg.Name,
		arg.Description,
		arg.Checksum,
		pq.Array(arg.CronSchedules),
		arg.FilePath,
		arg.Slug,
		arg.Name_2,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Checksum,
		&i.Description,
		pq.Array(&i.CronSchedules),
		&i.FilePath,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
