// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    name,
    description
) VALUES (
    $1, $2
) RETURNING id, uuid, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupByUUID = `-- name: DeleteGroupByUUID :exec
DELETE FROM groups WHERE uuid = $1
`

func (q *Queries) DeleteGroupByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupByUUID, argUuid)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, uuid, name, description, created_at, updated_at FROM groups
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupsWithUsers = `-- name: GetAllGroupsWithUsers :many
SELECT id, uuid, name, description, created_at, updated_at, users FROM group_view
`

func (q *Queries) GetAllGroupsWithUsers(ctx context.Context) ([]GroupView, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupView
	for rows.Next() {
		var i GroupView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE uuid = $1
`

func (q *Queries) GetGroupByUUID(ctx context.Context, argUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUUID, argUuid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByUUIDWithUsers = `-- name: GetGroupByUUIDWithUsers :one
SELECT id, uuid, name, description, created_at, updated_at, users FROM group_view WHERE uuid = $1
`

func (q *Queries) GetGroupByUUIDWithUsers(ctx context.Context, argUuid uuid.UUID) (GroupView, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUUIDWithUsers, argUuid)
	var i GroupView
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Users,
	)
	return i, err
}

const searchGroup = `-- name: SearchGroup :many
SELECT id, uuid, name, description, created_at, updated_at, users FROM group_view WHERE lower(name) LIKE '%' || lower($1::text) || '%' OR lower(description) LIKE '%' || lower($1::text) || '%'
`

func (q *Queries) SearchGroup(ctx context.Context, dollar_1 string) ([]GroupView, error) {
	rows, err := q.db.QueryContext(ctx, searchGroup, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupView
	for rows.Next() {
		var i GroupView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
