// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: groups.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    name,
    description
) VALUES (
    $1, $2
) RETURNING id, uuid, name, description, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroupByUUID = `-- name: DeleteGroupByUUID :exec
DELETE FROM groups WHERE uuid = $1
`

func (q *Queries) DeleteGroupByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupByUUID, argUuid)
	return err
}

const getAllGroups = `-- name: GetAllGroups :many
SELECT id, uuid, name, description, created_at, updated_at FROM groups
`

func (q *Queries) GetAllGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGroupsWithUsers = `-- name: GetAllGroupsWithUsers :many
SELECT id, uuid, name, description, created_at, updated_at, users FROM group_view
`

func (q *Queries) GetAllGroupsWithUsers(ctx context.Context) ([]GroupView, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupView
	for rows.Next() {
		var i GroupView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id int32) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE name = $1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT id, uuid, name, description, created_at, updated_at FROM groups WHERE uuid = $1
`

func (q *Queries) GetGroupByUUID(ctx context.Context, argUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUUID, argUuid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByUUIDWithUsers = `-- name: GetGroupByUUIDWithUsers :one
SELECT id, uuid, name, description, created_at, updated_at, users FROM group_view WHERE uuid = $1
`

func (q *Queries) GetGroupByUUIDWithUsers(ctx context.Context, argUuid uuid.UUID) (GroupView, error) {
	row := q.db.QueryRowContext(ctx, getGroupByUUIDWithUsers, argUuid)
	var i GroupView
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Users,
	)
	return i, err
}

const searchGroup = `-- name: SearchGroup :many
WITH filtered AS (
    SELECT id, uuid, name, description, created_at, updated_at, users
    FROM group_view
    WHERE lower(name) LIKE '%' || lower($1::text) || '%'
       OR lower(description) LIKE '%' || lower($1::text) || '%'
),
total AS (
    SELECT COUNT(*) AS total_count
    FROM filtered
),
paged AS (
    SELECT id, uuid, name, description, created_at, updated_at, users
    FROM filtered
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count
    FROM total
)
SELECT
    p.id, p.uuid, p.name, p.description, p.created_at, p.updated_at, p.users,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchGroupParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type SearchGroupRow struct {
	ID          int32          `db:"id" json:"id"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	Users       interface{}    `db:"users" json:"users"`
	PageCount   int64          `db:"page_count" json:"page_count"`
	TotalCount  int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchGroup(ctx context.Context, arg SearchGroupParams) ([]SearchGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, searchGroup, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchGroupRow
	for rows.Next() {
		var i SearchGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Users,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupByUUID = `-- name: UpdateGroupByUUID :one
UPDATE groups SET name = $1, description = $2 WHERE uuid = $3 RETURNING id, uuid, name, description, created_at, updated_at
`

type UpdateGroupByUUIDParams struct {
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateGroupByUUID(ctx context.Context, arg UpdateGroupByUUIDParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroupByUUID, arg.Name, arg.Description, arg.Uuid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
