// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repo

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ApprovalStatus string

const (
	ApprovalStatusPending  ApprovalStatus = "pending"
	ApprovalStatusApproved ApprovalStatus = "approved"
	ApprovalStatusRejected ApprovalStatus = "rejected"
)

func (e *ApprovalStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApprovalStatus(s)
	case string:
		*e = ApprovalStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApprovalStatus: %T", src)
	}
	return nil
}

type NullApprovalStatus struct {
	ApprovalStatus ApprovalStatus `json:"approval_status"`
	Valid          bool           `json:"valid"` // Valid is true if ApprovalStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApprovalStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApprovalStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApprovalStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApprovalStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApprovalStatus), nil
}

type AuthenticationMethod string

const (
	AuthenticationMethodPrivateKey AuthenticationMethod = "private_key"
	AuthenticationMethodPassword   AuthenticationMethod = "password"
)

func (e *AuthenticationMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthenticationMethod(s)
	case string:
		*e = AuthenticationMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthenticationMethod: %T", src)
	}
	return nil
}

type NullAuthenticationMethod struct {
	AuthenticationMethod AuthenticationMethod `json:"authentication_method"`
	Valid                bool                 `json:"valid"` // Valid is true if AuthenticationMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthenticationMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AuthenticationMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthenticationMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthenticationMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthenticationMethod), nil
}

type ConnectionType string

const (
	ConnectionTypeSsh  ConnectionType = "ssh"
	ConnectionTypeQssh ConnectionType = "qssh"
)

func (e *ConnectionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionType(s)
	case string:
		*e = ConnectionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionType: %T", src)
	}
	return nil
}

type NullConnectionType struct {
	ConnectionType ConnectionType `json:"connection_type"`
	Valid          bool           `json:"valid"` // Valid is true if ConnectionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionType) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionType), nil
}

type ExecutionStatus string

const (
	ExecutionStatusCancelled       ExecutionStatus = "cancelled"
	ExecutionStatusCompleted       ExecutionStatus = "completed"
	ExecutionStatusErrored         ExecutionStatus = "errored"
	ExecutionStatusPending         ExecutionStatus = "pending"
	ExecutionStatusPendingApproval ExecutionStatus = "pending_approval"
	ExecutionStatusRunning         ExecutionStatus = "running"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus `json:"execution_status"`
	Valid           bool            `json:"valid"` // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type TriggerType string

const (
	TriggerTypeManual    TriggerType = "manual"
	TriggerTypeScheduled TriggerType = "scheduled"
)

func (e *TriggerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TriggerType(s)
	case string:
		*e = TriggerType(s)
	default:
		return fmt.Errorf("unsupported scan type for TriggerType: %T", src)
	}
	return nil
}

type NullTriggerType struct {
	TriggerType TriggerType `json:"trigger_type"`
	Valid       bool        `json:"valid"` // Valid is true if TriggerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTriggerType) Scan(value interface{}) error {
	if value == nil {
		ns.TriggerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TriggerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTriggerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TriggerType), nil
}

type UserLoginType string

const (
	UserLoginTypeOidc     UserLoginType = "oidc"
	UserLoginTypeStandard UserLoginType = "standard"
	UserLoginTypeToken    UserLoginType = "token"
)

func (e *UserLoginType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserLoginType(s)
	case string:
		*e = UserLoginType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserLoginType: %T", src)
	}
	return nil
}

type NullUserLoginType struct {
	UserLoginType UserLoginType `json:"user_login_type"`
	Valid         bool          `json:"valid"` // Valid is true if UserLoginType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserLoginType) Scan(value interface{}) error {
	if value == nil {
		ns.UserLoginType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserLoginType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserLoginType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserLoginType), nil
}

type UserRoleType string

const (
	UserRoleTypeSuperuser UserRoleType = "superuser"
	UserRoleTypeUser      UserRoleType = "user"
)

func (e *UserRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoleType(s)
	case string:
		*e = UserRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoleType: %T", src)
	}
	return nil
}

type NullUserRoleType struct {
	UserRoleType UserRoleType `json:"user_role_type"`
	Valid        bool         `json:"valid"` // Valid is true if UserRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoleType), nil
}

type Approval struct {
	ID          int32          `db:"id" json:"id"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
	ExecLogID   int32          `db:"exec_log_id" json:"exec_log_id"`
	ActionID    string         `db:"action_id" json:"action_id"`
	Status      ApprovalStatus `db:"status" json:"status"`
	DecidedBy   sql.NullInt32  `db:"decided_by" json:"decided_by"`
	NamespaceID int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type CasbinRule struct {
	ID    int32          `db:"id" json:"id"`
	Ptype sql.NullString `db:"ptype" json:"ptype"`
	V0    sql.NullString `db:"v0" json:"v0"`
	V1    sql.NullString `db:"v1" json:"v1"`
	V2    sql.NullString `db:"v2" json:"v2"`
	V3    sql.NullString `db:"v3" json:"v3"`
	V4    sql.NullString `db:"v4" json:"v4"`
	V5    sql.NullString `db:"v5" json:"v5"`
}

type Credential struct {
	ID           int32        `db:"id" json:"id"`
	Uuid         uuid.UUID    `db:"uuid" json:"uuid"`
	Name         string       `db:"name" json:"name"`
	KeyType      string       `db:"key_type" json:"key_type"`
	KeyData      string       `db:"key_data" json:"key_data"`
	NamespaceID  int32        `db:"namespace_id" json:"namespace_id"`
	LastAccessed sql.NullTime `db:"last_accessed" json:"last_accessed"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at"`
}

type ExecutionLog struct {
	ID              int32           `db:"id" json:"id"`
	ExecID          string          `db:"exec_id" json:"exec_id"`
	FlowID          int32           `db:"flow_id" json:"flow_id"`
	Version         int32           `db:"version" json:"version"`
	Input           json.RawMessage `db:"input" json:"input"`
	Error           sql.NullString  `db:"error" json:"error"`
	CurrentActionID sql.NullString  `db:"current_action_id" json:"current_action_id"`
	Status          ExecutionStatus `db:"status" json:"status"`
	TriggerType     TriggerType     `db:"trigger_type" json:"trigger_type"`
	TriggeredBy     int32           `db:"triggered_by" json:"triggered_by"`
	NamespaceID     int32           `db:"namespace_id" json:"namespace_id"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
}

type Flow struct {
	ID           int32          `db:"id" json:"id"`
	Slug         string         `db:"slug" json:"slug"`
	Name         string         `db:"name" json:"name"`
	Checksum     string         `db:"checksum" json:"checksum"`
	Description  sql.NullString `db:"description" json:"description"`
	CronSchedule sql.NullString `db:"cron_schedule" json:"cron_schedule"`
	FilePath     string         `db:"file_path" json:"file_path"`
	NamespaceID  int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}

type FlowSecret struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	FlowID         int32          `db:"flow_id" json:"flow_id"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	NamespaceID    int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
}

type Group struct {
	ID          int32          `db:"id" json:"id"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

type GroupMembership struct {
	ID        int32     `db:"id" json:"id"`
	UserID    int32     `db:"user_id" json:"user_id"`
	GroupID   int32     `db:"group_id" json:"group_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type GroupView struct {
	ID          int32          `db:"id" json:"id"`
	Uuid        uuid.UUID      `db:"uuid" json:"uuid"`
	Name        string         `db:"name" json:"name"`
	Description sql.NullString `db:"description" json:"description"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	Users       interface{}    `db:"users" json:"users"`
}

type Namespace struct {
	ID        int32     `db:"id" json:"id"`
	Uuid      uuid.UUID `db:"uuid" json:"uuid"`
	Name      string    `db:"name" json:"name"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type NamespaceMember struct {
	ID          int32         `db:"id" json:"id"`
	Uuid        uuid.UUID     `db:"uuid" json:"uuid"`
	UserID      sql.NullInt32 `db:"user_id" json:"user_id"`
	GroupID     sql.NullInt32 `db:"group_id" json:"group_id"`
	NamespaceID int32         `db:"namespace_id" json:"namespace_id"`
	Role        string        `db:"role" json:"role"`
	CreatedAt   time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time     `db:"updated_at" json:"updated_at"`
}

type Node struct {
	ID             int32                `db:"id" json:"id"`
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	NamespaceID    int32                `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time            `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID        string          `db:"id" json:"id"`
	Data      json.RawMessage `db:"data" json:"data"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type User struct {
	ID        int32          `db:"id" json:"id"`
	Uuid      uuid.UUID      `db:"uuid" json:"uuid"`
	Name      string         `db:"name" json:"name"`
	Username  string         `db:"username" json:"username"`
	Password  sql.NullString `db:"password" json:"password"`
	LoginType UserLoginType  `db:"login_type" json:"login_type"`
	Role      UserRoleType   `db:"role" json:"role"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
}

type UserView struct {
	ID        int32          `db:"id" json:"id"`
	Uuid      uuid.UUID      `db:"uuid" json:"uuid"`
	Name      string         `db:"name" json:"name"`
	Username  string         `db:"username" json:"username"`
	Password  sql.NullString `db:"password" json:"password"`
	LoginType UserLoginType  `db:"login_type" json:"login_type"`
	Role      UserRoleType   `db:"role" json:"role"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
	Groups    interface{}    `db:"groups" json:"groups"`
}
