// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: namespaces.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignGroupNamespaceRole = `-- name: AssignGroupNamespaceRole :one
INSERT INTO namespace_members (group_id, namespace_id, role)
VALUES (
    (SELECT id FROM groups WHERE groups.uuid = $1),
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2),
    $3
)
ON CONFLICT ON CONSTRAINT unique_group_namespace
DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, uuid, user_id, group_id, namespace_id, role, created_at, updated_at
`

type AssignGroupNamespaceRoleParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Role   string    `db:"role" json:"role"`
}

func (q *Queries) AssignGroupNamespaceRole(ctx context.Context, arg AssignGroupNamespaceRoleParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, assignGroupNamespaceRole, arg.Uuid, arg.Uuid_2, arg.Role)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.GroupID,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignUserNamespaceRole = `-- name: AssignUserNamespaceRole :one
INSERT INTO namespace_members (user_id, namespace_id, role)
VALUES (
    (SELECT id FROM users WHERE users.uuid = $1),
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2),
    $3
)
ON CONFLICT ON CONSTRAINT unique_user_namespace
DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, uuid, user_id, group_id, namespace_id, role, created_at, updated_at
`

type AssignUserNamespaceRoleParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Role   string    `db:"role" json:"role"`
}

func (q *Queries) AssignUserNamespaceRole(ctx context.Context, arg AssignUserNamespaceRoleParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, assignUserNamespaceRole, arg.Uuid, arg.Uuid_2, arg.Role)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.GroupID,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name)
VALUES ($1)
RETURNING id, uuid, name, created_at, updated_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespaces WHERE uuid = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, argUuid)
	return err
}

const getAllNamespaceMembers = `-- name: GetAllNamespaceMembers :many
SELECT
    nm.uuid,
    COALESCE(u.uuid, g.uuid) as subject_uuid,
    CASE WHEN nm.user_id IS NOT NULL THEN 'user' ELSE 'group' END as subject_type,
    nm.role,
    nm.namespace_id,
    n.uuid as namespace_uuid,
    n.name as namespace_name,
    nm.created_at,
    nm.updated_at
FROM namespace_members nm
JOIN namespaces n ON nm.namespace_id = n.id
LEFT JOIN users u ON nm.user_id = u.id
LEFT JOIN groups g ON nm.group_id = g.id
ORDER BY n.name, nm.role
`

type GetAllNamespaceMembersRow struct {
	Uuid          uuid.UUID `db:"uuid" json:"uuid"`
	SubjectUuid   uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	SubjectType   string    `db:"subject_type" json:"subject_type"`
	Role          string    `db:"role" json:"role"`
	NamespaceID   int32     `db:"namespace_id" json:"namespace_id"`
	NamespaceUuid uuid.UUID `db:"namespace_uuid" json:"namespace_uuid"`
	NamespaceName string    `db:"namespace_name" json:"namespace_name"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetAllNamespaceMembers(ctx context.Context) ([]GetAllNamespaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllNamespaceMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllNamespaceMembersRow
	for rows.Next() {
		var i GetAllNamespaceMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.SubjectUuid,
			&i.SubjectType,
			&i.Role,
			&i.NamespaceID,
			&i.NamespaceUuid,
			&i.NamespaceName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllNamespaces = `-- name: GetAllNamespaces :many
SELECT id, uuid, name, created_at, updated_at FROM namespaces ORDER BY name
`

func (q *Queries) GetAllNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.QueryContext(ctx, getAllNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceByUUID = `-- name: GetNamespaceByUUID :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE uuid = $1
`

func (q *Queries) GetNamespaceByUUID(ctx context.Context, argUuid uuid.UUID) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByUUID, argUuid)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceMembers = `-- name: GetNamespaceMembers :many
SELECT
    nm.uuid,
    COALESCE(u.uuid, g.uuid) as subject_uuid,
    COALESCE(u.name, g.name) as subject_name,
    CASE WHEN nm.user_id IS NOT NULL THEN 'user' ELSE 'group' END as subject_type,
    nm.role,
    nm.created_at,
    nm.updated_at
FROM namespace_members nm
LEFT JOIN users u ON nm.user_id = u.id
LEFT JOIN groups g ON nm.group_id = g.id
WHERE nm.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
ORDER BY nm.role, subject_name
`

type GetNamespaceMembersRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	SubjectUuid uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	SubjectName string    `db:"subject_name" json:"subject_name"`
	SubjectType string    `db:"subject_type" json:"subject_type"`
	Role        string    `db:"role" json:"role"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNamespaceMembers(ctx context.Context, argUuid uuid.UUID) ([]GetNamespaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNamespaceMembers, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNamespaceMembersRow
	for rows.Next() {
		var i GetNamespaceMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.SubjectUuid,
			&i.SubjectName,
			&i.SubjectType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.uuid, g.name, g.description, g.created_at, g.updated_at FROM groups g
JOIN group_memberships gm ON g.id = gm.group_id
WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $1)
`

func (q *Queries) GetUserGroups(ctx context.Context, argUuid uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNamespacesWithRoles = `-- name: GetUserNamespacesWithRoles :many
WITH user_namespaces AS (
    -- Direct user membership
    SELECT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN users u ON nm.user_id = u.id
    WHERE u.uuid = $1

    UNION

    -- Group membership
    SELECT DISTINCT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN groups g ON nm.group_id = g.id
    JOIN group_memberships gm ON g.id = gm.group_id
    WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $1)
)
SELECT uuid, name, role FROM user_namespaces
ORDER BY name
`

type GetUserNamespacesWithRolesRow struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
	Role string    `db:"role" json:"role"`
}

func (q *Queries) GetUserNamespacesWithRoles(ctx context.Context, argUuid uuid.UUID) ([]GetUserNamespacesWithRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserNamespacesWithRoles, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamespacesWithRolesRow
	for rows.Next() {
		var i GetUserNamespacesWithRolesRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNamespaces = `-- name: ListNamespaces :many
WITH filtered AS (
    SELECT DISTINCT n.id, n.uuid, n.name, n.created_at, n.updated_at FROM namespaces n
    LEFT JOIN namespace_members nm ON n.id = nm.namespace_id
    LEFT JOIN users u ON nm.user_id = u.id
    LEFT JOIN groups g ON nm.group_id = g.id
    LEFT JOIN group_memberships gm ON g.id = gm.group_id
    WHERE (
        (SELECT role FROM users WHERE users.uuid = $1) = 'superuser'
        OR u.uuid = $1
        OR gm.user_id = (SELECT id FROM users WHERE users.uuid = $1)
    ) AND lower(n.name) LIKE '%' || lower($4::text) || '%'
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, created_at, updated_at FROM filtered
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT
    p.id, p.uuid, p.name, p.created_at, p.updated_at,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListNamespacesParams struct {
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
	Column4 string    `db:"column_4" json:"column_4"`
}

type ListNamespacesRow struct {
	ID         int32     `db:"id" json:"id"`
	Uuid       uuid.UUID `db:"uuid" json:"uuid"`
	Name       string    `db:"name" json:"name"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
	PageCount  int64     `db:"page_count" json:"page_count"`
	TotalCount int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]ListNamespacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces,
		arg.Uuid,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespacesRow
	for rows.Next() {
		var i ListNamespacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNamespaceMember = `-- name: RemoveNamespaceMember :one
DELETE FROM namespace_members
WHERE namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
AND namespace_members.uuid = $2
RETURNING id, uuid, user_id, group_id, namespace_id, role, created_at, updated_at
`

type RemoveNamespaceMemberParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) RemoveNamespaceMember(ctx context.Context, arg RemoveNamespaceMemberParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, removeNamespaceMember, arg.Uuid, arg.Uuid_2)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.GroupID,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNamespace = `-- name: UpdateNamespace :one
UPDATE namespaces
SET name = $2, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, created_at, updated_at
`

type UpdateNamespaceParams struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, updateNamespace, arg.Uuid, arg.Name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNamespaceMember = `-- name: UpdateNamespaceMember :one
UPDATE namespace_members
SET role = $3, updated_at = NOW()
WHERE namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
AND namespace_members.uuid = $2
RETURNING id, uuid, user_id, group_id, namespace_id, role, created_at, updated_at
`

type UpdateNamespaceMemberParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Role   string    `db:"role" json:"role"`
}

func (q *Queries) UpdateNamespaceMember(ctx context.Context, arg UpdateNamespaceMemberParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, updateNamespaceMember, arg.Uuid, arg.Uuid_2, arg.Role)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.GroupID,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
