// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: namespaces.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const assignGroupNamespaceRole = `-- name: AssignGroupNamespaceRole :one
INSERT INTO namespace_members (subject_uuid, subject_type, namespace_id, role)
VALUES (
    $1,
    'group',
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2),
    $3
)
ON CONFLICT ON CONSTRAINT unique_namespace_member
DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, uuid, subject_uuid, subject_type, namespace_id, role, created_at, updated_at
`

type AssignGroupNamespaceRoleParams struct {
	SubjectUuid uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Role        string    `db:"role" json:"role"`
}

func (q *Queries) AssignGroupNamespaceRole(ctx context.Context, arg AssignGroupNamespaceRoleParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, assignGroupNamespaceRole, arg.SubjectUuid, arg.Uuid, arg.Role)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubjectUuid,
		&i.SubjectType,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignUserNamespaceRole = `-- name: AssignUserNamespaceRole :one
INSERT INTO namespace_members (subject_uuid, subject_type, namespace_id, role)
VALUES (
    $1,
    'user',
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2),
    $3
)
ON CONFLICT ON CONSTRAINT unique_namespace_member
DO UPDATE SET role = EXCLUDED.role, updated_at = NOW()
RETURNING id, uuid, subject_uuid, subject_type, namespace_id, role, created_at, updated_at
`

type AssignUserNamespaceRoleParams struct {
	SubjectUuid uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	Role        string    `db:"role" json:"role"`
}

func (q *Queries) AssignUserNamespaceRole(ctx context.Context, arg AssignUserNamespaceRoleParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, assignUserNamespaceRole, arg.SubjectUuid, arg.Uuid, arg.Role)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubjectUuid,
		&i.SubjectType,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkUserNamespaceAccess = `-- name: CheckUserNamespaceAccess :one
SELECT EXISTS (
    SELECT 1 FROM group_namespace_access gna
    JOIN group_memberships gm ON gna.group_id = gm.group_id
    WHERE gm.user_id = $1 AND gna.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
) AS has_access
`

type CheckUserNamespaceAccessParams struct {
	UserID int32     `db:"user_id" json:"user_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) CheckUserNamespaceAccess(ctx context.Context, arg CheckUserNamespaceAccessParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserNamespaceAccess, arg.UserID, arg.Uuid)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name)
VALUES ($1)
RETURNING id, uuid, name, created_at, updated_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespaces WHERE uuid = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, argUuid)
	return err
}

const getAllNamespaces = `-- name: GetAllNamespaces :many
SELECT id, uuid, name, created_at, updated_at FROM namespaces ORDER BY name
`

func (q *Queries) GetAllNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.QueryContext(ctx, getAllNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsWithNamespaceAccess = `-- name: GetGroupsWithNamespaceAccess :many
SELECT g.id, g.uuid, g.name, g.description, g.created_at, g.updated_at, gna.created_at AS access_granted_at
FROM groups g
JOIN group_namespace_access gna ON g.id = gna.group_id
WHERE gna.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
`

type GetGroupsWithNamespaceAccessRow struct {
	ID              int32          `db:"id" json:"id"`
	Uuid            uuid.UUID      `db:"uuid" json:"uuid"`
	Name            string         `db:"name" json:"name"`
	Description     sql.NullString `db:"description" json:"description"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updated_at"`
	AccessGrantedAt time.Time      `db:"access_granted_at" json:"access_granted_at"`
}

func (q *Queries) GetGroupsWithNamespaceAccess(ctx context.Context, argUuid uuid.UUID) ([]GetGroupsWithNamespaceAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsWithNamespaceAccess, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsWithNamespaceAccessRow
	for rows.Next() {
		var i GetGroupsWithNamespaceAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessGrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceByUUID = `-- name: GetNamespaceByUUID :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE uuid = $1
`

func (q *Queries) GetNamespaceByUUID(ctx context.Context, argUuid uuid.UUID) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByUUID, argUuid)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceMembers = `-- name: GetNamespaceMembers :many
SELECT
    nm.uuid,
    CASE WHEN nm.subject_type = 'user' THEN u.uuid ELSE g.uuid END as subject_uuid,
    CASE WHEN nm.subject_type = 'user' THEN u.name ELSE g.name END as subject_name,
    nm.subject_type,
    nm.role,
    nm.created_at,
    nm.updated_at
FROM namespace_members nm
LEFT JOIN users u ON nm.subject_uuid = u.uuid AND nm.subject_type = 'user'
LEFT JOIN groups g ON nm.subject_uuid = g.uuid AND nm.subject_type = 'group'
WHERE nm.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
ORDER BY nm.role, subject_name
`

type GetNamespaceMembersRow struct {
	Uuid        uuid.UUID   `db:"uuid" json:"uuid"`
	SubjectUuid interface{} `db:"subject_uuid" json:"subject_uuid"`
	SubjectName interface{} `db:"subject_name" json:"subject_name"`
	SubjectType string      `db:"subject_type" json:"subject_type"`
	Role        string      `db:"role" json:"role"`
	CreatedAt   time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time   `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetNamespaceMembers(ctx context.Context, argUuid uuid.UUID) ([]GetNamespaceMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getNamespaceMembers, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNamespaceMembersRow
	for rows.Next() {
		var i GetNamespaceMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.SubjectUuid,
			&i.SubjectName,
			&i.SubjectType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespacesForGroup = `-- name: GetNamespacesForGroup :many
SELECT n.id, n.uuid, n.name, n.created_at, n.updated_at, gna.created_at AS access_granted_at
FROM namespaces n
JOIN group_namespace_access gna ON n.id = gna.namespace_id
WHERE gna.group_id = (SELECT id FROM groups WHERE groups.uuid = $1)
`

type GetNamespacesForGroupRow struct {
	ID              int32     `db:"id" json:"id"`
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Name            string    `db:"name" json:"name"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
	AccessGrantedAt time.Time `db:"access_granted_at" json:"access_granted_at"`
}

func (q *Queries) GetNamespacesForGroup(ctx context.Context, argUuid uuid.UUID) ([]GetNamespacesForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, getNamespacesForGroup, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNamespacesForGroupRow
	for rows.Next() {
		var i GetNamespacesForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessGrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.uuid, g.name, g.description, g.created_at, g.updated_at FROM groups g
JOIN group_memberships gm ON g.id = gm.group_id
WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $1)
`

func (q *Queries) GetUserGroups(ctx context.Context, argUuid uuid.UUID) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNamespacesWithRoles = `-- name: GetUserNamespacesWithRoles :many
WITH user_namespaces AS (
    -- Direct user membership
    SELECT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    WHERE nm.subject_uuid = (SELECT uuid FROM users WHERE users.uuid = $1)
    AND nm.subject_type = 'user'

    UNION

    -- Group membership
    SELECT DISTINCT n.uuid, n.name, nm.role
    FROM namespaces n
    JOIN namespace_members nm ON n.id = nm.namespace_id
    JOIN groups gr ON nm.subject_uuid = gr.uuid
    JOIN group_memberships gm ON gr.id = gm.group_id
    WHERE gm.user_id = (SELECT id FROM users WHERE users.uuid = $1)
    AND nm.subject_type = 'group'
)
SELECT uuid, name, role FROM user_namespaces
ORDER BY name
`

type GetUserNamespacesWithRolesRow struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
	Role string    `db:"role" json:"role"`
}

func (q *Queries) GetUserNamespacesWithRoles(ctx context.Context, argUuid uuid.UUID) ([]GetUserNamespacesWithRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserNamespacesWithRoles, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamespacesWithRolesRow
	for rows.Next() {
		var i GetUserNamespacesWithRolesRow
		if err := rows.Scan(&i.Uuid, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantGroupNamespaceAccess = `-- name: GrantGroupNamespaceAccess :one
INSERT INTO group_namespace_access (group_id, namespace_id)
VALUES (
    (SELECT id FROM groups WHERE groups.uuid = $1),
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
)
ON CONFLICT (group_id, namespace_id) DO NOTHING
RETURNING id, group_id, namespace_id, created_at
`

type GrantGroupNamespaceAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) GrantGroupNamespaceAccess(ctx context.Context, arg GrantGroupNamespaceAccessParams) (GroupNamespaceAccess, error) {
	row := q.db.QueryRowContext(ctx, grantGroupNamespaceAccess, arg.Uuid, arg.Uuid_2)
	var i GroupNamespaceAccess
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.NamespaceID,
		&i.CreatedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
WITH filtered AS (
    SELECT DISTINCT n.id, n.uuid, n.name, n.created_at, n.updated_at FROM namespaces n
    LEFT JOIN namespace_members nm_user ON n.id = nm_user.namespace_id AND nm_user.subject_type = 'user'
    LEFT JOIN namespace_members nm_group ON n.id = nm_group.namespace_id AND nm_group.subject_type = 'group'
    LEFT JOIN group_memberships gm ON nm_group.subject_uuid IN (
        SELECT g.uuid FROM groups g 
        JOIN group_memberships gm2 ON g.id = gm2.group_id 
        WHERE gm2.user_id = (SELECT id FROM users WHERE users.uuid = $1)
    )
    WHERE (
        (SELECT role FROM users WHERE users.uuid = $1) = 'superuser'
        OR nm_user.subject_uuid = $1
        OR nm_group.subject_uuid IN (
            SELECT g.uuid FROM groups g 
            JOIN group_memberships gm3 ON g.id = gm3.group_id 
            WHERE gm3.user_id = (SELECT id FROM users WHERE users.uuid = $1)
        )
    )
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, created_at, updated_at FROM filtered
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT COUNT(*) AS page_count FROM paged
)
SELECT
    p.id, p.uuid, p.name, p.created_at, p.updated_at,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListNamespacesParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListNamespacesRow struct {
	ID         int32     `db:"id" json:"id"`
	Uuid       uuid.UUID `db:"uuid" json:"uuid"`
	Name       string    `db:"name" json:"name"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
	PageCount  int64     `db:"page_count" json:"page_count"`
	TotalCount int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]ListNamespacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespacesRow
	for rows.Next() {
		var i ListNamespacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNamespaceMember = `-- name: RemoveNamespaceMember :one
DELETE FROM namespace_members
WHERE namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
AND namespace_members.uuid = $2
RETURNING id, uuid, subject_uuid, subject_type, namespace_id, role, created_at, updated_at
`

type RemoveNamespaceMemberParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) RemoveNamespaceMember(ctx context.Context, arg RemoveNamespaceMemberParams) (NamespaceMember, error) {
	row := q.db.QueryRowContext(ctx, removeNamespaceMember, arg.Uuid, arg.Uuid_2)
	var i NamespaceMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.SubjectUuid,
		&i.SubjectType,
		&i.NamespaceID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeGroupNamespaceAccess = `-- name: RevokeGroupNamespaceAccess :exec
DELETE FROM group_namespace_access
WHERE group_id = (SELECT id FROM groups WHERE groups.uuid = $1)
AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type RevokeGroupNamespaceAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) RevokeGroupNamespaceAccess(ctx context.Context, arg RevokeGroupNamespaceAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeGroupNamespaceAccess, arg.Uuid, arg.Uuid_2)
	return err
}

const updateNamespace = `-- name: UpdateNamespace :one
UPDATE namespaces
SET name = $2, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, created_at, updated_at
`

type UpdateNamespaceParams struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, updateNamespace, arg.Uuid, arg.Name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
