// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: namespaces.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkUserNamespaceAccess = `-- name: CheckUserNamespaceAccess :one
SELECT EXISTS (
    SELECT 1 FROM group_namespace_access gna
    JOIN group_memberships gm ON gna.group_id = gm.group_id
    WHERE gm.user_id = $1 AND gna.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
) AS has_access
`

type CheckUserNamespaceAccessParams struct {
	UserID int32     `db:"user_id" json:"user_id"`
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) CheckUserNamespaceAccess(ctx context.Context, arg CheckUserNamespaceAccessParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserNamespaceAccess, arg.UserID, arg.Uuid)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name)
VALUES ($1)
RETURNING id, uuid, name, created_at, updated_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespaces WHERE uuid = $1
`

func (q *Queries) DeleteNamespace(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, argUuid)
	return err
}

const getGroupsWithNamespaceAccess = `-- name: GetGroupsWithNamespaceAccess :many
SELECT g.id, g.uuid, g.name, g.description, g.created_at, g.updated_at, gna.created_at AS access_granted_at
FROM groups g
JOIN group_namespace_access gna ON g.id = gna.group_id
WHERE gna.namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $1)
`

type GetGroupsWithNamespaceAccessRow struct {
	ID              int32          `db:"id" json:"id"`
	Uuid            uuid.UUID      `db:"uuid" json:"uuid"`
	Name            string         `db:"name" json:"name"`
	Description     sql.NullString `db:"description" json:"description"`
	CreatedAt       time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time      `db:"updated_at" json:"updated_at"`
	AccessGrantedAt time.Time      `db:"access_granted_at" json:"access_granted_at"`
}

func (q *Queries) GetGroupsWithNamespaceAccess(ctx context.Context, argUuid uuid.UUID) ([]GetGroupsWithNamespaceAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsWithNamespaceAccess, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsWithNamespaceAccessRow
	for rows.Next() {
		var i GetGroupsWithNamespaceAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessGrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespaceByUUID = `-- name: GetNamespaceByUUID :one
SELECT id, uuid, name, created_at, updated_at FROM namespaces WHERE uuid = $1
`

func (q *Queries) GetNamespaceByUUID(ctx context.Context, argUuid uuid.UUID) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceByUUID, argUuid)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNamespacesForGroup = `-- name: GetNamespacesForGroup :many
SELECT n.id, n.uuid, n.name, n.created_at, n.updated_at, gna.created_at AS access_granted_at
FROM namespaces n
JOIN group_namespace_access gna ON n.id = gna.namespace_id
WHERE gna.group_id = (SELECT id FROM groups WHERE groups.uuid = $1)
`

type GetNamespacesForGroupRow struct {
	ID              int32     `db:"id" json:"id"`
	Uuid            uuid.UUID `db:"uuid" json:"uuid"`
	Name            string    `db:"name" json:"name"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
	AccessGrantedAt time.Time `db:"access_granted_at" json:"access_granted_at"`
}

func (q *Queries) GetNamespacesForGroup(ctx context.Context, argUuid uuid.UUID) ([]GetNamespacesForGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, getNamespacesForGroup, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNamespacesForGroupRow
	for rows.Next() {
		var i GetNamespacesForGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccessGrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const grantGroupNamespaceAccess = `-- name: GrantGroupNamespaceAccess :one
INSERT INTO group_namespace_access (group_id, namespace_id)
VALUES (
    (SELECT id FROM groups WHERE groups.uuid = $1),
    (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
)
ON CONFLICT (group_id, namespace_id) DO NOTHING
RETURNING id, group_id, namespace_id, created_at
`

type GrantGroupNamespaceAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) GrantGroupNamespaceAccess(ctx context.Context, arg GrantGroupNamespaceAccessParams) (GroupNamespaceAccess, error) {
	row := q.db.QueryRowContext(ctx, grantGroupNamespaceAccess, arg.Uuid, arg.Uuid_2)
	var i GroupNamespaceAccess
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.NamespaceID,
		&i.CreatedAt,
	)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
WITH filtered AS (
    SELECT id, uuid, name, created_at, updated_at FROM namespaces
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, created_at, updated_at FROM filtered
    LIMIT $1 OFFSET $2
),
page_count AS (
    SELECT COUNT(*) AS page_count FROM paged
)
SELECT 
    p.id, p.uuid, p.name, p.created_at, p.updated_at,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListNamespacesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListNamespacesRow struct {
	ID         int32     `db:"id" json:"id"`
	Uuid       uuid.UUID `db:"uuid" json:"uuid"`
	Name       string    `db:"name" json:"name"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at"`
	PageCount  int64     `db:"page_count" json:"page_count"`
	TotalCount int64     `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]ListNamespacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespacesRow
	for rows.Next() {
		var i ListNamespacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGroupNamespaceAccess = `-- name: RevokeGroupNamespaceAccess :exec
DELETE FROM group_namespace_access 
WHERE group_id = (SELECT id FROM groups WHERE groups.uuid = $1) 
AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type RevokeGroupNamespaceAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) RevokeGroupNamespaceAccess(ctx context.Context, arg RevokeGroupNamespaceAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeGroupNamespaceAccess, arg.Uuid, arg.Uuid_2)
	return err
}

const updateNamespace = `-- name: UpdateNamespace :one
UPDATE namespaces
SET name = $2, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, created_at, updated_at
`

type UpdateNamespaceParams struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) (Namespace, error) {
	row := q.db.QueryRowContext(ctx, updateNamespace, arg.Uuid, arg.Name)
	var i Namespace
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
