// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: namespace_secrets.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createNamespaceSecret = `-- name: CreateNamespaceSecret :one
INSERT INTO namespace_secrets (key, encrypted_value, description, namespace_id)
VALUES ($1, $2, $3, (SELECT id FROM namespaces WHERE namespaces.uuid = $4))
RETURNING id, uuid, key, encrypted_value, description, namespace_id, created_at, updated_at
`

type CreateNamespaceSecretParams struct {
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
}

func (q *Queries) CreateNamespaceSecret(ctx context.Context, arg CreateNamespaceSecretParams) (NamespaceSecret, error) {
	row := q.db.QueryRowContext(ctx, createNamespaceSecret,
		arg.Key,
		arg.EncryptedValue,
		arg.Description,
		arg.Uuid,
	)
	var i NamespaceSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNamespaceSecret = `-- name: DeleteNamespaceSecret :exec
DELETE FROM namespace_secrets
WHERE namespace_secrets.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteNamespaceSecretParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteNamespaceSecret(ctx context.Context, arg DeleteNamespaceSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteNamespaceSecret, arg.Uuid, arg.Uuid_2)
	return err
}

const getDecryptedNamespaceSecrets = `-- name: GetDecryptedNamespaceSecrets :many
SELECT ns.key, ns.encrypted_value FROM namespace_secrets ns
JOIN namespaces n ON ns.namespace_id = n.id
WHERE n.uuid = $1
`

type GetDecryptedNamespaceSecretsRow struct {
	Key            string `db:"key" json:"key"`
	EncryptedValue string `db:"encrypted_value" json:"encrypted_value"`
}

// Used internally for execution - returns all secrets for a namespace
func (q *Queries) GetDecryptedNamespaceSecrets(ctx context.Context, argUuid uuid.UUID) ([]GetDecryptedNamespaceSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDecryptedNamespaceSecrets, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDecryptedNamespaceSecretsRow
	for rows.Next() {
		var i GetDecryptedNamespaceSecretsRow
		if err := rows.Scan(&i.Key, &i.EncryptedValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespaceSecretByUUID = `-- name: GetNamespaceSecretByUUID :one
SELECT ns.id, ns.uuid, ns.key, ns.encrypted_value, ns.description, ns.namespace_id, ns.created_at, ns.updated_at, n.uuid AS namespace_uuid FROM namespace_secrets ns
JOIN namespaces n ON ns.namespace_id = n.id
WHERE ns.uuid = $1 AND n.uuid = $2
`

type GetNamespaceSecretByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetNamespaceSecretByUUIDRow struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	NamespaceID    int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNamespaceSecretByUUID(ctx context.Context, arg GetNamespaceSecretByUUIDParams) (GetNamespaceSecretByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceSecretByUUID, arg.Uuid, arg.Uuid_2)
	var i GetNamespaceSecretByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const listNamespaceSecrets = `-- name: ListNamespaceSecrets :many
SELECT ns.id, ns.uuid, ns.key, ns.encrypted_value, ns.description, ns.namespace_id, ns.created_at, ns.updated_at, n.uuid AS namespace_uuid FROM namespace_secrets ns
JOIN namespaces n ON ns.namespace_id = n.id
WHERE n.uuid = $1
ORDER BY ns.created_at DESC
`

type ListNamespaceSecretsRow struct {
	ID             int32          `db:"id" json:"id"`
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
	NamespaceID    int32          `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time      `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID      `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) ListNamespaceSecrets(ctx context.Context, argUuid uuid.UUID) ([]ListNamespaceSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaceSecrets, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNamespaceSecretsRow
	for rows.Next() {
		var i ListNamespaceSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Key,
			&i.EncryptedValue,
			&i.Description,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNamespaceSecret = `-- name: UpdateNamespaceSecret :one
UPDATE namespace_secrets SET
    key = $3,
    encrypted_value = $4,
    description = $5,
    updated_at = NOW()
WHERE namespace_secrets.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
RETURNING id, uuid, key, encrypted_value, description, namespace_id, created_at, updated_at
`

type UpdateNamespaceSecretParams struct {
	Uuid           uuid.UUID      `db:"uuid" json:"uuid"`
	Uuid_2         uuid.UUID      `db:"uuid_2" json:"uuid_2"`
	Key            string         `db:"key" json:"key"`
	EncryptedValue string         `db:"encrypted_value" json:"encrypted_value"`
	Description    sql.NullString `db:"description" json:"description"`
}

func (q *Queries) UpdateNamespaceSecret(ctx context.Context, arg UpdateNamespaceSecretParams) (NamespaceSecret, error) {
	row := q.db.QueryRowContext(ctx, updateNamespaceSecret,
		arg.Uuid,
		arg.Uuid_2,
		arg.Key,
		arg.EncryptedValue,
		arg.Description,
	)
	var i NamespaceSecret
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Key,
		&i.EncryptedValue,
		&i.Description,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
