// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: nodes.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, hostname, port, username, os_family, tags, auth_method, connection_type, credential_id, namespace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, (SELECT id FROM namespaces WHERE namespaces.uuid = $10))
RETURNING id, uuid, name, hostname, port, username, os_family, tags, auth_method, connection_type, credential_id, namespace_id, created_at, updated_at
`

type CreateNodeParams struct {
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.Name,
		arg.Hostname,
		arg.Port,
		arg.Username,
		arg.OsFamily,
		pq.Array(arg.Tags),
		arg.AuthMethod,
		arg.ConnectionType,
		arg.CredentialID,
		arg.Uuid,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.ConnectionType,
		&i.CredentialID,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE nodes.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $2)
`

type DeleteNodeParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) DeleteNode(ctx context.Context, arg DeleteNodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteNode, arg.Uuid, arg.Uuid_2)
	return err
}

const getNodeByName = `-- name: GetNodeByName :one
SELECT n.id, n.uuid, n.name, n.hostname, n.port, n.username, n.os_family, n.tags, n.auth_method, n.connection_type, n.credential_id, n.namespace_id, n.created_at, n.updated_at, ns.uuid AS namespace_uuid FROM nodes n
JOIN namespaces ns ON n.namespace_id = ns.id
WHERE n.name = $1 AND ns.uuid = $2
`

type GetNodeByNameParams struct {
	Name string    `db:"name" json:"name"`
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
}

type GetNodeByNameRow struct {
	ID             int32                `db:"id" json:"id"`
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	NamespaceID    int32                `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time            `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID            `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNodeByName(ctx context.Context, arg GetNodeByNameParams) (GetNodeByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeByName, arg.Name, arg.Uuid)
	var i GetNodeByNameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.ConnectionType,
		&i.CredentialID,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT n.id, n.uuid, n.name, n.hostname, n.port, n.username, n.os_family, n.tags, n.auth_method, n.connection_type, n.credential_id, n.namespace_id, n.created_at, n.updated_at, ns.uuid AS namespace_uuid FROM nodes n
JOIN namespaces ns ON n.namespace_id = ns.id
WHERE n.uuid = $1 AND ns.uuid = $2
`

type GetNodeByUUIDParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetNodeByUUIDRow struct {
	ID             int32                `db:"id" json:"id"`
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	NamespaceID    int32                `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time            `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID            `db:"namespace_uuid" json:"namespace_uuid"`
}

func (q *Queries) GetNodeByUUID(ctx context.Context, arg GetNodeByUUIDParams) (GetNodeByUUIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, arg.Uuid, arg.Uuid_2)
	var i GetNodeByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.ConnectionType,
		&i.CredentialID,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamespaceUuid,
	)
	return i, err
}

const getNodesByNames = `-- name: GetNodesByNames :many
WITH updated_credentials AS (
    UPDATE credentials 
    SET last_accessed = NOW() 
    WHERE id IN (
        SELECT DISTINCT n.credential_id 
        FROM nodes n 
        JOIN namespaces ns ON n.namespace_id = ns.id 
        WHERE n.name = ANY($1::text[]) AND ns.uuid = $2 AND n.credential_id IS NOT NULL
    )
    RETURNING id, uuid, name, key_type, key_data, namespace_id, last_accessed, created_at, updated_at
)
SELECT 
    n.id, n.uuid, n.name, n.hostname, n.port, n.username, n.os_family, n.tags, n.auth_method, n.connection_type, n.credential_id, n.namespace_id, n.created_at, n.updated_at,
    ns.uuid AS namespace_uuid,
    c.uuid AS credential_uuid, 
    c.name AS credential_name, 
    c.key_type AS credential_key_type, 
    c.key_data AS credential_key_data
FROM nodes n
JOIN namespaces ns ON n.namespace_id = ns.id
LEFT JOIN credentials c ON n.credential_id = c.id
WHERE n.name = ANY($1::text[]) AND ns.uuid = $2
ORDER BY n.name
`

type GetNodesByNamesParams struct {
	Column1 []string  `db:"column_1" json:"column_1"`
	Uuid    uuid.UUID `db:"uuid" json:"uuid"`
}

type GetNodesByNamesRow struct {
	ID                int32                `db:"id" json:"id"`
	Uuid              uuid.UUID            `db:"uuid" json:"uuid"`
	Name              string               `db:"name" json:"name"`
	Hostname          string               `db:"hostname" json:"hostname"`
	Port              int32                `db:"port" json:"port"`
	Username          string               `db:"username" json:"username"`
	OsFamily          string               `db:"os_family" json:"os_family"`
	Tags              []string             `db:"tags" json:"tags"`
	AuthMethod        AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType    ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID      sql.NullInt32        `db:"credential_id" json:"credential_id"`
	NamespaceID       int32                `db:"namespace_id" json:"namespace_id"`
	CreatedAt         time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time            `db:"updated_at" json:"updated_at"`
	NamespaceUuid     uuid.UUID            `db:"namespace_uuid" json:"namespace_uuid"`
	CredentialUuid    uuid.NullUUID        `db:"credential_uuid" json:"credential_uuid"`
	CredentialName    sql.NullString       `db:"credential_name" json:"credential_name"`
	CredentialKeyType sql.NullString       `db:"credential_key_type" json:"credential_key_type"`
	CredentialKeyData sql.NullString       `db:"credential_key_data" json:"credential_key_data"`
}

func (q *Queries) GetNodesByNames(ctx context.Context, arg GetNodesByNamesParams) ([]GetNodesByNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNodesByNames, pq.Array(arg.Column1), arg.Uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNodesByNamesRow
	for rows.Next() {
		var i GetNodesByNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Hostname,
			&i.Port,
			&i.Username,
			&i.OsFamily,
			pq.Array(&i.Tags),
			&i.AuthMethod,
			&i.ConnectionType,
			&i.CredentialID,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.CredentialUuid,
			&i.CredentialName,
			&i.CredentialKeyType,
			&i.CredentialKeyData,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
WITH filtered AS (
    SELECT n.id, n.uuid, n.name, n.hostname, n.port, n.username, n.os_family, n.tags, n.auth_method, n.connection_type, n.credential_id, n.namespace_id, n.created_at, n.updated_at, ns.uuid AS namespace_uuid FROM nodes n
    JOIN namespaces ns ON n.namespace_id = ns.id
    WHERE ns.uuid = $1
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, hostname, port, username, os_family, tags, auth_method, connection_type, credential_id, namespace_id, created_at, updated_at, namespace_uuid FROM filtered
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count FROM total
)
SELECT 
    p.id, p.uuid, p.name, p.hostname, p.port, p.username, p.os_family, p.tags, p.auth_method, p.connection_type, p.credential_id, p.namespace_id, p.created_at, p.updated_at, p.namespace_uuid,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListNodesParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListNodesRow struct {
	ID             int32                `db:"id" json:"id"`
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	NamespaceID    int32                `db:"namespace_id" json:"namespace_id"`
	CreatedAt      time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time            `db:"updated_at" json:"updated_at"`
	NamespaceUuid  uuid.UUID            `db:"namespace_uuid" json:"namespace_uuid"`
	PageCount      int64                `db:"page_count" json:"page_count"`
	TotalCount     int64                `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodes, arg.Uuid, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesRow
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Hostname,
			&i.Port,
			&i.Username,
			&i.OsFamily,
			pq.Array(&i.Tags),
			&i.AuthMethod,
			&i.ConnectionType,
			&i.CredentialID,
			&i.NamespaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamespaceUuid,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET name = $2, hostname = $3, port = $4, username = $5, os_family = $6, tags = $7, auth_method = $8, connection_type = $9, credential_id = $10, updated_at = NOW()
WHERE nodes.uuid = $1 AND namespace_id = (SELECT id FROM namespaces WHERE namespaces.uuid = $11)
RETURNING id, uuid, name, hostname, port, username, os_family, tags, auth_method, connection_type, credential_id, namespace_id, created_at, updated_at
`

type UpdateNodeParams struct {
	Uuid           uuid.UUID            `db:"uuid" json:"uuid"`
	Name           string               `db:"name" json:"name"`
	Hostname       string               `db:"hostname" json:"hostname"`
	Port           int32                `db:"port" json:"port"`
	Username       string               `db:"username" json:"username"`
	OsFamily       string               `db:"os_family" json:"os_family"`
	Tags           []string             `db:"tags" json:"tags"`
	AuthMethod     AuthenticationMethod `db:"auth_method" json:"auth_method"`
	ConnectionType ConnectionType       `db:"connection_type" json:"connection_type"`
	CredentialID   sql.NullInt32        `db:"credential_id" json:"credential_id"`
	Uuid_2         uuid.UUID            `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Uuid,
		arg.Name,
		arg.Hostname,
		arg.Port,
		arg.Username,
		arg.OsFamily,
		pq.Array(arg.Tags),
		arg.AuthMethod,
		arg.ConnectionType,
		arg.CredentialID,
		arg.Uuid_2,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.ConnectionType,
		&i.CredentialID,
		&i.NamespaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
