// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: nodes.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, hostname, port, username, os_family, tags, auth_method, credential_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, uuid, name, hostname, port, username, os_family, tags, auth_method, credential_id, created_at, updated_at
`

type CreateNodeParams struct {
	Name         string               `db:"name" json:"name"`
	Hostname     string               `db:"hostname" json:"hostname"`
	Port         int32                `db:"port" json:"port"`
	Username     string               `db:"username" json:"username"`
	OsFamily     string               `db:"os_family" json:"os_family"`
	Tags         []string             `db:"tags" json:"tags"`
	AuthMethod   AuthenticationMethod `db:"auth_method" json:"auth_method"`
	CredentialID int32                `db:"credential_id" json:"credential_id"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, createNode,
		arg.Name,
		arg.Hostname,
		arg.Port,
		arg.Username,
		arg.OsFamily,
		pq.Array(arg.Tags),
		arg.AuthMethod,
		arg.CredentialID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.CredentialID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE uuid = $1
`

func (q *Queries) DeleteNode(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNode, argUuid)
	return err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT id, uuid, name, hostname, port, username, os_family, tags, auth_method, credential_id, created_at, updated_at FROM nodes WHERE uuid = $1
`

func (q *Queries) GetNodeByUUID(ctx context.Context, argUuid uuid.UUID) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, argUuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.CredentialID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodes = `-- name: ListNodes :many
WITH filtered AS (
    SELECT id, uuid, name, hostname, port, username, os_family, tags, auth_method, credential_id, created_at, updated_at FROM nodes
),
total AS (
    SELECT COUNT(*) AS total_count FROM filtered
),
paged AS (
    SELECT id, uuid, name, hostname, port, username, os_family, tags, auth_method, credential_id, created_at, updated_at FROM filtered
    LIMIT $1 OFFSET $2
),
page_count AS (
    SELECT COUNT(*) AS page_count FROM paged
)
SELECT 
    p.id, p.uuid, p.name, p.hostname, p.port, p.username, p.os_family, p.tags, p.auth_method, p.credential_id, p.created_at, p.updated_at,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type ListNodesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListNodesRow struct {
	ID           int32                `db:"id" json:"id"`
	Uuid         uuid.UUID            `db:"uuid" json:"uuid"`
	Name         string               `db:"name" json:"name"`
	Hostname     string               `db:"hostname" json:"hostname"`
	Port         int32                `db:"port" json:"port"`
	Username     string               `db:"username" json:"username"`
	OsFamily     string               `db:"os_family" json:"os_family"`
	Tags         []string             `db:"tags" json:"tags"`
	AuthMethod   AuthenticationMethod `db:"auth_method" json:"auth_method"`
	CredentialID int32                `db:"credential_id" json:"credential_id"`
	CreatedAt    time.Time            `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time            `db:"updated_at" json:"updated_at"`
	PageCount    int64                `db:"page_count" json:"page_count"`
	TotalCount   int64                `db:"total_count" json:"total_count"`
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]ListNodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesRow
	for rows.Next() {
		var i ListNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Hostname,
			&i.Port,
			&i.Username,
			&i.OsFamily,
			pq.Array(&i.Tags),
			&i.AuthMethod,
			&i.CredentialID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET name = $2, hostname = $3, port = $4, username = $5, os_family = $6, tags = $7, auth_method = $8, credential_id = $9, updated_at = NOW()
WHERE uuid = $1
RETURNING id, uuid, name, hostname, port, username, os_family, tags, auth_method, credential_id, created_at, updated_at
`

type UpdateNodeParams struct {
	Uuid         uuid.UUID            `db:"uuid" json:"uuid"`
	Name         string               `db:"name" json:"name"`
	Hostname     string               `db:"hostname" json:"hostname"`
	Port         int32                `db:"port" json:"port"`
	Username     string               `db:"username" json:"username"`
	OsFamily     string               `db:"os_family" json:"os_family"`
	Tags         []string             `db:"tags" json:"tags"`
	AuthMethod   AuthenticationMethod `db:"auth_method" json:"auth_method"`
	CredentialID int32                `db:"credential_id" json:"credential_id"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Uuid,
		arg.Name,
		arg.Hostname,
		arg.Port,
		arg.Username,
		arg.OsFamily,
		pq.Array(arg.Tags),
		arg.AuthMethod,
		arg.CredentialID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Hostname,
		&i.Port,
		&i.Username,
		&i.OsFamily,
		pq.Array(&i.Tags),
		&i.AuthMethod,
		&i.CredentialID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
