// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: prefix_access.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const assignGroupPrefixAccess = `-- name: AssignGroupPrefixAccess :exec
INSERT INTO prefix_access (group_id, namespace_id, prefix_id)
VALUES ((SELECT groups.id FROM groups WHERE groups.uuid = $1),
        (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2),
        (SELECT flow_prefixes.id FROM flow_prefixes WHERE flow_prefixes.name = $3 AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)))
ON CONFLICT ON CONSTRAINT unique_group_prefix DO NOTHING
`

type AssignGroupPrefixAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) AssignGroupPrefixAccess(ctx context.Context, arg AssignGroupPrefixAccessParams) error {
	_, err := q.db.ExecContext(ctx, assignGroupPrefixAccess, arg.Uuid, arg.Uuid_2, arg.Name)
	return err
}

const assignUserPrefixAccess = `-- name: AssignUserPrefixAccess :exec
INSERT INTO prefix_access (user_id, namespace_id, prefix_id)
VALUES ((SELECT users.id FROM users WHERE users.uuid = $1),
        (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2),
        (SELECT flow_prefixes.id FROM flow_prefixes WHERE flow_prefixes.name = $3 AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)))
ON CONFLICT ON CONSTRAINT unique_user_prefix DO NOTHING
`

type AssignUserPrefixAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) AssignUserPrefixAccess(ctx context.Context, arg AssignUserPrefixAccessParams) error {
	_, err := q.db.ExecContext(ctx, assignUserPrefixAccess, arg.Uuid, arg.Uuid_2, arg.Name)
	return err
}

const getAllPrefixAccesses = `-- name: GetAllPrefixAccesses :many
SELECT pa.uuid,
       COALESCE(u.uuid, g.uuid) as subject_uuid,
       CASE WHEN pa.user_id IS NOT NULL THEN 'user' ELSE 'group' END as subject_type,
       n.uuid as namespace_uuid,
       fp.name as prefix,
       pa.created_at
FROM prefix_access pa
JOIN namespaces n ON pa.namespace_id = n.id
JOIN flow_prefixes fp ON pa.prefix_id = fp.id
LEFT JOIN users u ON pa.user_id = u.id
LEFT JOIN groups g ON pa.group_id = g.id
`

type GetAllPrefixAccessesRow struct {
	Uuid          uuid.UUID `db:"uuid" json:"uuid"`
	SubjectUuid   uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	SubjectType   string    `db:"subject_type" json:"subject_type"`
	NamespaceUuid uuid.UUID `db:"namespace_uuid" json:"namespace_uuid"`
	Prefix        string    `db:"prefix" json:"prefix"`
	CreatedAt     time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) GetAllPrefixAccesses(ctx context.Context) ([]GetAllPrefixAccessesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPrefixAccesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPrefixAccessesRow
	for rows.Next() {
		var i GetAllPrefixAccessesRow
		if err := rows.Scan(
			&i.Uuid,
			&i.SubjectUuid,
			&i.SubjectType,
			&i.NamespaceUuid,
			&i.Prefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberPrefixes = `-- name: GetMemberPrefixes :many
SELECT fp.name as prefix, pa.created_at FROM prefix_access pa
JOIN flow_prefixes fp ON pa.prefix_id = fp.id
WHERE pa.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1)
AND (
    pa.user_id = (SELECT nm.user_id FROM namespace_members nm WHERE nm.uuid = $2)
    OR pa.group_id = (SELECT nm.group_id FROM namespace_members nm WHERE nm.uuid = $2)
)
`

type GetMemberPrefixesParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

type GetMemberPrefixesRow struct {
	Prefix    string    `db:"prefix" json:"prefix"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) GetMemberPrefixes(ctx context.Context, arg GetMemberPrefixesParams) ([]GetMemberPrefixesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMemberPrefixes, arg.Uuid, arg.Uuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberPrefixesRow
	for rows.Next() {
		var i GetMemberPrefixesRow
		if err := rows.Scan(&i.Prefix, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrefixMembers = `-- name: GetPrefixMembers :many
SELECT pa.uuid, COALESCE(u.uuid, g.uuid) as subject_uuid,
       COALESCE(u.name, g.name) as subject_name,
       CASE WHEN pa.user_id IS NOT NULL THEN 'user' ELSE 'group' END as subject_type,
       fp.name as prefix, pa.created_at
FROM prefix_access pa
JOIN flow_prefixes fp ON pa.prefix_id = fp.id
LEFT JOIN users u ON pa.user_id = u.id
LEFT JOIN groups g ON pa.group_id = g.id
WHERE pa.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1)
AND fp.name = $2
`

type GetPrefixMembersParams struct {
	Uuid uuid.UUID `db:"uuid" json:"uuid"`
	Name string    `db:"name" json:"name"`
}

type GetPrefixMembersRow struct {
	Uuid        uuid.UUID `db:"uuid" json:"uuid"`
	SubjectUuid uuid.UUID `db:"subject_uuid" json:"subject_uuid"`
	SubjectName string    `db:"subject_name" json:"subject_name"`
	SubjectType string    `db:"subject_type" json:"subject_type"`
	Prefix      string    `db:"prefix" json:"prefix"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) GetPrefixMembers(ctx context.Context, arg GetPrefixMembersParams) ([]GetPrefixMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrefixMembers, arg.Uuid, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrefixMembersRow
	for rows.Next() {
		var i GetPrefixMembersRow
		if err := rows.Scan(
			&i.Uuid,
			&i.SubjectUuid,
			&i.SubjectName,
			&i.SubjectType,
			&i.Prefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccessiblePrefixes = `-- name: GetUserAccessiblePrefixes :many
SELECT DISTINCT fp.name as prefix FROM prefix_access pa
JOIN flow_prefixes fp ON pa.prefix_id = fp.id
WHERE pa.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1)
AND (
    pa.user_id = (SELECT users.id FROM users WHERE users.uuid = $2)
    OR pa.group_id IN (SELECT gm.group_id FROM group_memberships gm JOIN users u ON gm.user_id = u.id WHERE u.uuid = $2)
)
`

type GetUserAccessiblePrefixesParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) GetUserAccessiblePrefixes(ctx context.Context, arg GetUserAccessiblePrefixesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserAccessiblePrefixes, arg.Uuid, arg.Uuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var prefix string
		if err := rows.Scan(&prefix); err != nil {
			return nil, err
		}
		items = append(items, prefix)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllMemberPrefixAccess = `-- name: RevokeAllMemberPrefixAccess :exec
DELETE FROM prefix_access
WHERE namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $1)
AND (
    user_id = (SELECT nm.user_id FROM namespace_members nm WHERE nm.uuid = $2)
    OR group_id = (SELECT nm.group_id FROM namespace_members nm WHERE nm.uuid = $2)
)
`

type RevokeAllMemberPrefixAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
}

func (q *Queries) RevokeAllMemberPrefixAccess(ctx context.Context, arg RevokeAllMemberPrefixAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllMemberPrefixAccess, arg.Uuid, arg.Uuid_2)
	return err
}

const revokeGroupPrefixAccess = `-- name: RevokeGroupPrefixAccess :exec
DELETE FROM prefix_access
WHERE group_id = (SELECT groups.id FROM groups WHERE groups.uuid = $1)
AND namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
AND prefix_id = (SELECT flow_prefixes.id FROM flow_prefixes WHERE flow_prefixes.name = $3 AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2))
`

type RevokeGroupPrefixAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) RevokeGroupPrefixAccess(ctx context.Context, arg RevokeGroupPrefixAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeGroupPrefixAccess, arg.Uuid, arg.Uuid_2, arg.Name)
	return err
}

const revokeUserPrefixAccess = `-- name: RevokeUserPrefixAccess :exec
DELETE FROM prefix_access
WHERE user_id = (SELECT users.id FROM users WHERE users.uuid = $1)
AND namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2)
AND prefix_id = (SELECT flow_prefixes.id FROM flow_prefixes WHERE flow_prefixes.name = $3 AND flow_prefixes.namespace_id = (SELECT namespaces.id FROM namespaces WHERE namespaces.uuid = $2))
`

type RevokeUserPrefixAccessParams struct {
	Uuid   uuid.UUID `db:"uuid" json:"uuid"`
	Uuid_2 uuid.UUID `db:"uuid_2" json:"uuid_2"`
	Name   string    `db:"name" json:"name"`
}

func (q *Queries) RevokeUserPrefixAccess(ctx context.Context, arg RevokeUserPrefixAccessParams) error {
	_, err := q.db.ExecContext(ctx, revokeUserPrefixAccess, arg.Uuid, arg.Uuid_2, arg.Name)
	return err
}
