// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	AddApprovalRequest(ctx context.Context, arg AddApprovalRequestParams) (AddApprovalRequestRow, error)
	AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error)
	AddGroupToUserByUUID(ctx context.Context, arg AddGroupToUserByUUIDParams) error
	ApproveRequestByUUID(ctx context.Context, arg ApproveRequestByUUIDParams) (ApproveRequestByUUIDRow, error)
	CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFlows(ctx context.Context) error
	DeleteGroupByUUID(ctx context.Context, argUuid uuid.UUID) error
	DeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) error
	GetAllGroups(ctx context.Context) ([]Group, error)
	GetAllGroupsWithUsers(ctx context.Context) ([]GroupView, error)
	GetAllUsersWithGroups(ctx context.Context) ([]UserView, error)
	GetApprovalByUUID(ctx context.Context, argUuid uuid.UUID) (GetApprovalByUUIDRow, error)
	GetApprovalRequestForActionAndExec(ctx context.Context, arg GetApprovalRequestForActionAndExecParams) (Approval, error)
	GetChildrenByParentUUID(ctx context.Context, parentExecID sql.NullString) ([]ExecutionLog, error)
	GetExecutionByExecID(ctx context.Context, execID string) (GetExecutionByExecIDRow, error)
	GetExecutionByID(ctx context.Context, id int32) (ExecutionLog, error)
	GetExecutionsByFlow(ctx context.Context, arg GetExecutionsByFlowParams) ([]ExecutionLog, error)
	GetFlowBySlug(ctx context.Context, slug string) (Flow, error)
	GetFlowFromExecID(ctx context.Context, execID string) (GetFlowFromExecIDRow, error)
	GetGroupByUUID(ctx context.Context, argUuid uuid.UUID) (Group, error)
	GetGroupByUUIDWithUsers(ctx context.Context, argUuid uuid.UUID) (GroupView, error)
	GetInputForExecByUUID(ctx context.Context, execID string) (json.RawMessage, error)
	GetPendingApprovalRequestForExec(ctx context.Context, execID string) (GetPendingApprovalRequestForExecRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByUUIDWithGroups(ctx context.Context, argUuid uuid.UUID) (UserView, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameWithGroups(ctx context.Context, username string) (UserView, error)
	RejectRequestByUUID(ctx context.Context, arg RejectRequestByUUIDParams) (RejectRequestByUUIDRow, error)
	RemoveAllGroupsForUserByUUID(ctx context.Context, userUuid uuid.UUID) error
	SearchGroup(ctx context.Context, dollar_1 string) ([]GroupView, error)
	SearchUsersWithGroups(ctx context.Context, dollar_1 string) ([]UserView, error)
	UpdateApprovalStatusByUUID(ctx context.Context, arg UpdateApprovalStatusByUUIDParams) (UpdateApprovalStatusByUUIDRow, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error)
	UpdateUserByUUID(ctx context.Context, arg UpdateUserByUUIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
