// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddExecutionLog(ctx context.Context, arg AddExecutionLogParams) (ExecutionLog, error)
	CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllFlows(ctx context.Context) error
	GetFlowBySlug(ctx context.Context, slug string) (Flow, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPassword(ctx context.Context, id int32) (sql.NullString, error)
	UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (ExecutionLog, error)
	UpdateFlow(ctx context.Context, arg UpdateFlowParams) (Flow, error)
}

var _ Querier = (*Queries)(nil)
