// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: scheduler.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const cancelTasksByExecID = `-- name: CancelTasksByExecID :exec
UPDATE scheduler_tasks SET status = 'cancelled' WHERE exec_id = $1 AND status = 'pending'
`

func (q *Queries) CancelTasksByExecID(ctx context.Context, execID string) error {
	_, err := q.db.ExecContext(ctx, cancelTasksByExecID, execID)
	return err
}

const createSchedulerTask = `-- name: CreateSchedulerTask :one
INSERT INTO scheduler_tasks (uuid, exec_id, payload, status) 
VALUES ($1, $2, $3, $4) RETURNING id, uuid, exec_id, payload, status, created_at
`

type CreateSchedulerTaskParams struct {
	Uuid    uuid.UUID       `db:"uuid" json:"uuid"`
	ExecID  string          `db:"exec_id" json:"exec_id"`
	Payload json.RawMessage `db:"payload" json:"payload"`
	Status  string          `db:"status" json:"status"`
}

// Immediate task operations
func (q *Queries) CreateSchedulerTask(ctx context.Context, arg CreateSchedulerTaskParams) (SchedulerTask, error) {
	row := q.db.QueryRowContext(ctx, createSchedulerTask,
		arg.Uuid,
		arg.ExecID,
		arg.Payload,
		arg.Status,
	)
	var i SchedulerTask
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExecID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingTasks = `-- name: GetPendingTasks :many
SELECT id, uuid, exec_id, payload, status, created_at FROM scheduler_tasks 
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingTasks(ctx context.Context, limit int32) ([]SchedulerTask, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerTask
	for rows.Next() {
		var i SchedulerTask
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ExecID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE scheduler_tasks SET status = $1 WHERE id = $2
`

type UpdateTaskStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int32  `db:"id" json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
