// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repo

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    login_type,
    role,
    name
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, uuid, name, username, password, login_type, role, created_at, updated_at
`

type CreateUserParams struct {
	Username  string         `db:"username" json:"username"`
	Password  sql.NullString `db:"password" json:"password"`
	LoginType UserLoginType  `db:"login_type" json:"login_type"`
	Role      UserRoleType   `db:"role" json:"role"`
	Name      string         `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.LoginType,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByUUID = `-- name: DeleteUserByUUID :exec
DELETE FROM users WHERE uuid = $1
`

func (q *Queries) DeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUUID, argUuid)
	return err
}

const getAllUsersWithGroups = `-- name: GetAllUsersWithGroups :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view
`

func (q *Queries) GetAllUsersWithGroups(ctx context.Context) ([]UserView, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersWithGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserView
	for rows.Next() {
		var i UserView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameWithGroups = `-- name: GetUserByUsernameWithGroups :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view WHERE username = $1
`

func (q *Queries) GetUserByUsernameWithGroups(ctx context.Context, username string) (UserView, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameWithGroups, username)
	var i UserView
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Groups,
	)
	return i, err
}

const searchUsersWithGroups = `-- name: SearchUsersWithGroups :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view WHERE lower(name) LIKE '%' || lower($1::text) || '%' OR lower(username) LIKE '%' || lower($1::text) || '%'
`

func (q *Queries) SearchUsersWithGroups(ctx context.Context, dollar_1 string) ([]UserView, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersWithGroups, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserView
	for rows.Next() {
		var i UserView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
