// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repo

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addGroupToUserByUUID = `-- name: AddGroupToUserByUUID :exec
WITH
user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $1
),
group_lookup AS (
    SELECT id FROM groups WHERE groups.uuid = $2
)
INSERT INTO group_memberships (user_id, group_id) VALUES (
    ( SELECT id FROM user_lookup ),
    ( SELECT id FROM group_lookup )
)
`

type AddGroupToUserByUUIDParams struct {
	UserUuid  uuid.UUID `db:"user_uuid" json:"user_uuid"`
	GroupUuid uuid.UUID `db:"group_uuid" json:"group_uuid"`
}

func (q *Queries) AddGroupToUserByUUID(ctx context.Context, arg AddGroupToUserByUUIDParams) error {
	_, err := q.db.ExecContext(ctx, addGroupToUserByUUID, arg.UserUuid, arg.GroupUuid)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    password,
    login_type,
    role,
    name
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, uuid, name, username, password, login_type, role, created_at, updated_at
`

type CreateUserParams struct {
	Username  string         `db:"username" json:"username"`
	Password  sql.NullString `db:"password" json:"password"`
	LoginType UserLoginType  `db:"login_type" json:"login_type"`
	Role      UserRoleType   `db:"role" json:"role"`
	Name      string         `db:"name" json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.LoginType,
		arg.Role,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByUUID = `-- name: DeleteUserByUUID :exec
DELETE FROM users WHERE uuid = $1
`

func (q *Queries) DeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUUID, argUuid)
	return err
}

const getAllUsersWithGroups = `-- name: GetAllUsersWithGroups :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view
`

func (q *Queries) GetAllUsersWithGroups(ctx context.Context) ([]UserView, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersWithGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserView
	for rows.Next() {
		var i UserView
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE uuid = $1
`

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, argUuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUUIDWithGroups = `-- name: GetUserByUUIDWithGroups :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view WHERE uuid = $1
`

func (q *Queries) GetUserByUUIDWithGroups(ctx context.Context, argUuid uuid.UUID) (UserView, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUIDWithGroups, argUuid)
	var i UserView
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Groups,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameWithGroups = `-- name: GetUserByUsernameWithGroups :one
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups FROM user_view WHERE username = $1
`

func (q *Queries) GetUserByUsernameWithGroups(ctx context.Context, username string) (UserView, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameWithGroups, username)
	var i UserView
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Groups,
	)
	return i, err
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at FROM users WHERE role = $1
`

func (q *Queries) GetUsersByRole(ctx context.Context, role UserRoleType) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllGroupsForUserByUUID = `-- name: RemoveAllGroupsForUserByUUID :exec
WITH
user_lookup AS (
    SELECT id FROM users WHERE users.uuid = $1
)
DELETE FROM group_memberships WHERE user_id = ( SELECT id FROM user_lookup )
`

func (q *Queries) RemoveAllGroupsForUserByUUID(ctx context.Context, userUuid uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllGroupsForUserByUUID, userUuid)
	return err
}

const searchUsersWithGroups = `-- name: SearchUsersWithGroups :many
WITH filtered AS (
    SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups
    FROM user_view
    WHERE lower(name) LIKE '%' || lower($1::text) || '%'
       OR lower(username) LIKE '%' || lower($1::text) || '%'
),
total AS (
    SELECT COUNT(*) AS total_count
    FROM filtered
),
paged AS (
    SELECT id, uuid, name, username, password, login_type, role, created_at, updated_at, groups
    FROM filtered
    LIMIT $2 OFFSET $3
),
page_count AS (
    SELECT CEIL(total.total_count::numeric / $2::numeric)::bigint AS page_count
    FROM total
)
SELECT
    p.id, p.uuid, p.name, p.username, p.password, p.login_type, p.role, p.created_at, p.updated_at, p.groups,
    pc.page_count,
    t.total_count
FROM paged p, page_count pc, total t
`

type SearchUsersWithGroupsParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type SearchUsersWithGroupsRow struct {
	ID         int32          `db:"id" json:"id"`
	Uuid       uuid.UUID      `db:"uuid" json:"uuid"`
	Name       string         `db:"name" json:"name"`
	Username   string         `db:"username" json:"username"`
	Password   sql.NullString `db:"password" json:"password"`
	LoginType  UserLoginType  `db:"login_type" json:"login_type"`
	Role       UserRoleType   `db:"role" json:"role"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time      `db:"updated_at" json:"updated_at"`
	Groups     interface{}    `db:"groups" json:"groups"`
	PageCount  int64          `db:"page_count" json:"page_count"`
	TotalCount int64          `db:"total_count" json:"total_count"`
}

func (q *Queries) SearchUsersWithGroups(ctx context.Context, arg SearchUsersWithGroupsParams) ([]SearchUsersWithGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsersWithGroups, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersWithGroupsRow
	for rows.Next() {
		var i SearchUsersWithGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.LoginType,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Groups,
			&i.PageCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserByUUID = `-- name: UpdateUserByUUID :one
UPDATE users SET name = $1, username = $2 WHERE uuid = $3 RETURNING id, uuid, name, username, password, login_type, role, created_at, updated_at
`

type UpdateUserByUUIDParams struct {
	Name     string    `db:"name" json:"name"`
	Username string    `db:"username" json:"username"`
	Uuid     uuid.UUID `db:"uuid" json:"uuid"`
}

func (q *Queries) UpdateUserByUUID(ctx context.Context, arg UpdateUserByUUIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByUUID, arg.Name, arg.Username, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordByUsername = `-- name: UpdateUserPasswordByUsername :one
UPDATE users SET password = $2 WHERE username = $1 RETURNING id, uuid, name, username, password, login_type, role, created_at, updated_at
`

type UpdateUserPasswordByUsernameParams struct {
	Username string         `db:"username" json:"username"`
	Password sql.NullString `db:"password" json:"password"`
}

func (q *Queries) UpdateUserPasswordByUsername(ctx context.Context, arg UpdateUserPasswordByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPasswordByUsername, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Username,
		&i.Password,
		&i.LoginType,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
