name: Approve PR from Issue
on:
  pull_request:
    types: [opened, edited, reopened]

permissions:
  pull-requests: write
  issues: read

jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: knadh/approve-pr-creation-from-issue@v1.0.0
        with:
          exclude_past_contributors: "true"
